package com.rent.entity;

public class House {
    @Override
    public String toString() {
        return "House{" +
                "houseid=" + houseid +
                ", publishuserid=" + publishuserid +
                ", cityname='" + cityname + '\'' +
                ", communityname='" + communityname + '\'' +
                ", buildingnumber='" + buildingnumber + '\'' +
                ", housetype=" + housetype +
                ", housearea=" + housearea +
                ", floornumber=" + floornumber +
                ", elevatorornot=" + elevatorornot +
                ", housedescription='" + housedescription + '\'' +
                ", photonum=" + photonum +
                ", depositmoney=" + depositmoney +
                ", paymentmethod=" + paymentmethod +
                ", rentmoney=" + rentmoney +
                ", registtime='" + registtime + '\'' +
                ", updatetime='" + updatetime + '\'' +
                ", housestatus=" + housestatus +
                '}';
    }


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rentsystem..house.houseId
     *
     * @mbggenerated Sat Jan 05 21:07:16 CST 2019
     */
    private Integer houseid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rentsystem..house.publishUserId
     *
     * @mbggenerated Sat Jan 05 21:07:16 CST 2019
     */
    private Integer publishuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rentsystem..house.cityName
     *
     * @mbggenerated Sat Jan 05 21:07:16 CST 2019
     */
    private String cityname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rentsystem..house.communityName
     *
     * @mbggenerated Sat Jan 05 21:07:16 CST 2019
     */
    private String communityname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rentsystem..house.buildingNumber
     *
     * @mbggenerated Sat Jan 05 21:07:16 CST 2019
     */
    private String buildingnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rentsystem..house.houseType
     *
     * @mbggenerated Sat Jan 05 21:07:16 CST 2019
     */
    private Integer housetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rentsystem..house.houseArea
     *
     * @mbggenerated Sat Jan 05 21:07:16 CST 2019
     */
    private Integer housearea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rentsystem..house.floorNumber
     *
     * @mbggenerated Sat Jan 05 21:07:16 CST 2019
     */
    private Integer floornumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rentsystem..house.elevatorOrNot
     *
     * @mbggenerated Sat Jan 05 21:07:16 CST 2019
     */
    private Integer elevatorornot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rentsystem..house.houseDescription
     *
     * @mbggenerated Sat Jan 05 21:07:16 CST 2019
     */
    private String housedescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rentsystem..house.photoNum
     *
     * @mbggenerated Sat Jan 05 21:07:16 CST 2019
     */
    private Integer photonum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rentsystem..house.depositMoney
     *
     * @mbggenerated Sat Jan 05 21:07:16 CST 2019
     */
    private Float depositmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rentsystem..house.paymentMethod
     *
     * @mbggenerated Sat Jan 05 21:07:16 CST 2019
     */
    private Integer paymentmethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rentsystem..house.rentMoney
     *
     * @mbggenerated Sat Jan 05 21:07:16 CST 2019
     */
    private Float rentmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rentsystem..house.registTime
     *
     * @mbggenerated Sat Jan 05 21:07:16 CST 2019
     */
    private String registtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rentsystem..house.updateTime
     *
     * @mbggenerated Sat Jan 05 21:07:16 CST 2019
     */
    private String updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rentsystem..house.houseStatus
     *
     * @mbggenerated Sat Jan 05 21:07:16 CST 2019
     */
    private Integer housestatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rentsystem..house.houseId
     *
     * @return the value of rentsystem..house.houseId
     *
     * @mbggenerated Sat Jan 05 21:07:16 CST 2019
     */
    public Integer getHouseid() {
        return houseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rentsystem..house.houseId
     *
     * @param houseid the value for rentsystem..house.houseId
     *
     * @mbggenerated Sat Jan 05 21:07:16 CST 2019
     */
    public void setHouseid(Integer houseid) {
        this.houseid = houseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rentsystem..house.publishUserId
     *
     * @return the value of rentsystem..house.publishUserId
     *
     * @mbggenerated Sat Jan 05 21:07:16 CST 2019
     */
    public Integer getPublishuserid() {
        return publishuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rentsystem..house.publishUserId
     *
     * @param publishuserid the value for rentsystem..house.publishUserId
     *
     * @mbggenerated Sat Jan 05 21:07:16 CST 2019
     */
    public void setPublishuserid(Integer publishuserid) {
        this.publishuserid = publishuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rentsystem..house.cityName
     *
     * @return the value of rentsystem..house.cityName
     *
     * @mbggenerated Sat Jan 05 21:07:16 CST 2019
     */
    public String getCityname() {
        return cityname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rentsystem..house.cityName
     *
     * @param cityname the value for rentsystem..house.cityName
     *
     * @mbggenerated Sat Jan 05 21:07:16 CST 2019
     */
    public void setCityname(String cityname) {
        this.cityname = cityname == null ? null : cityname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rentsystem..house.communityName
     *
     * @return the value of rentsystem..house.communityName
     *
     * @mbggenerated Sat Jan 05 21:07:16 CST 2019
     */
    public String getCommunityname() {
        return communityname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rentsystem..house.communityName
     *
     * @param communityname the value for rentsystem..house.communityName
     *
     * @mbggenerated Sat Jan 05 21:07:16 CST 2019
     */
    public void setCommunityname(String communityname) {
        this.communityname = communityname == null ? null : communityname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rentsystem..house.buildingNumber
     *
     * @return the value of rentsystem..house.buildingNumber
     *
     * @mbggenerated Sat Jan 05 21:07:16 CST 2019
     */
    public String getBuildingnumber() {
        return buildingnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rentsystem..house.buildingNumber
     *
     * @param buildingnumber the value for rentsystem..house.buildingNumber
     *
     * @mbggenerated Sat Jan 05 21:07:16 CST 2019
     */
    public void setBuildingnumber(String buildingnumber) {
        this.buildingnumber = buildingnumber == null ? null : buildingnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rentsystem..house.houseType
     *
     * @return the value of rentsystem..house.houseType
     *
     * @mbggenerated Sat Jan 05 21:07:16 CST 2019
     */
    public Integer getHousetype() {
        return housetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rentsystem..house.houseType
     *
     * @param housetype the value for rentsystem..house.houseType
     *
     * @mbggenerated Sat Jan 05 21:07:16 CST 2019
     */
    public void setHousetype(Integer housetype) {
        this.housetype = housetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rentsystem..house.houseArea
     *
     * @return the value of rentsystem..house.houseArea
     *
     * @mbggenerated Sat Jan 05 21:07:16 CST 2019
     */
    public Integer getHousearea() {
        return housearea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rentsystem..house.houseArea
     *
     * @param housearea the value for rentsystem..house.houseArea
     *
     * @mbggenerated Sat Jan 05 21:07:16 CST 2019
     */
    public void setHousearea(Integer housearea) {
        this.housearea = housearea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rentsystem..house.floorNumber
     *
     * @return the value of rentsystem..house.floorNumber
     *
     * @mbggenerated Sat Jan 05 21:07:16 CST 2019
     */
    public Integer getFloornumber() {
        return floornumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rentsystem..house.floorNumber
     *
     * @param floornumber the value for rentsystem..house.floorNumber
     *
     * @mbggenerated Sat Jan 05 21:07:16 CST 2019
     */
    public void setFloornumber(Integer floornumber) {
        this.floornumber = floornumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rentsystem..house.elevatorOrNot
     *
     * @return the value of rentsystem..house.elevatorOrNot
     *
     * @mbggenerated Sat Jan 05 21:07:16 CST 2019
     */
    public Integer getElevatorornot() {
        return elevatorornot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rentsystem..house.elevatorOrNot
     *
     * @param elevatorornot the value for rentsystem..house.elevatorOrNot
     *
     * @mbggenerated Sat Jan 05 21:07:16 CST 2019
     */
    public void setElevatorornot(Integer elevatorornot) {
        this.elevatorornot = elevatorornot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rentsystem..house.houseDescription
     *
     * @return the value of rentsystem..house.houseDescription
     *
     * @mbggenerated Sat Jan 05 21:07:16 CST 2019
     */
    public String getHousedescription() {
        return housedescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rentsystem..house.houseDescription
     *
     * @param housedescription the value for rentsystem..house.houseDescription
     *
     * @mbggenerated Sat Jan 05 21:07:16 CST 2019
     */
    public void setHousedescription(String housedescription) {
        this.housedescription = housedescription == null ? null : housedescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rentsystem..house.photoNum
     *
     * @return the value of rentsystem..house.photoNum
     *
     * @mbggenerated Sat Jan 05 21:07:16 CST 2019
     */
    public Integer getPhotonum() {
        return photonum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rentsystem..house.photoNum
     *
     * @param photonum the value for rentsystem..house.photoNum
     *
     * @mbggenerated Sat Jan 05 21:07:16 CST 2019
     */
    public void setPhotonum(Integer photonum) {
        this.photonum = photonum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rentsystem..house.depositMoney
     *
     * @return the value of rentsystem..house.depositMoney
     *
     * @mbggenerated Sat Jan 05 21:07:16 CST 2019
     */
    public Float getDepositmoney() {
        return depositmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rentsystem..house.depositMoney
     *
     * @param depositmoney the value for rentsystem..house.depositMoney
     *
     * @mbggenerated Sat Jan 05 21:07:16 CST 2019
     */
    public void setDepositmoney(Float depositmoney) {
        this.depositmoney = depositmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rentsystem..house.paymentMethod
     *
     * @return the value of rentsystem..house.paymentMethod
     *
     * @mbggenerated Sat Jan 05 21:07:16 CST 2019
     */
    public Integer getPaymentmethod() {
        return paymentmethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rentsystem..house.paymentMethod
     *
     * @param paymentmethod the value for rentsystem..house.paymentMethod
     *
     * @mbggenerated Sat Jan 05 21:07:16 CST 2019
     */
    public void setPaymentmethod(Integer paymentmethod) {
        this.paymentmethod = paymentmethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rentsystem..house.rentMoney
     *
     * @return the value of rentsystem..house.rentMoney
     *
     * @mbggenerated Sat Jan 05 21:07:16 CST 2019
     */
    public Float getRentmoney() {
        return rentmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rentsystem..house.rentMoney
     *
     * @param rentmoney the value for rentsystem..house.rentMoney
     *
     * @mbggenerated Sat Jan 05 21:07:16 CST 2019
     */
    public void setRentmoney(Float rentmoney) {
        this.rentmoney = rentmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rentsystem..house.registTime
     *
     * @return the value of rentsystem..house.registTime
     *
     * @mbggenerated Sat Jan 05 21:07:16 CST 2019
     */
    public String getRegisttime() {
        return registtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rentsystem..house.registTime
     *
     * @param registtime the value for rentsystem..house.registTime
     *
     * @mbggenerated Sat Jan 05 21:07:16 CST 2019
     */
    public void setRegisttime(String registtime) {
        this.registtime = registtime == null ? null : registtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rentsystem..house.updateTime
     *
     * @return the value of rentsystem..house.updateTime
     *
     * @mbggenerated Sat Jan 05 21:07:16 CST 2019
     */
    public String getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rentsystem..house.updateTime
     *
     * @param updatetime the value for rentsystem..house.updateTime
     *
     * @mbggenerated Sat Jan 05 21:07:16 CST 2019
     */
    public void setUpdatetime(String updatetime) {
        this.updatetime = updatetime == null ? null : updatetime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rentsystem..house.houseStatus
     *
     * @return the value of rentsystem..house.houseStatus
     *
     * @mbggenerated Sat Jan 05 21:07:16 CST 2019
     */
    public Integer getHousestatus() {
        return housestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rentsystem..house.houseStatus
     *
     * @param housestatus the value for rentsystem..house.houseStatus
     *
     * @mbggenerated Sat Jan 05 21:07:16 CST 2019
     */
    public void setHousestatus(Integer housestatus) {
        this.housestatus = housestatus;
    }
}