package com.rent.entity;

import java.util.ArrayList;
import java.util.List;

public class HouseExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rentsystem..house
     *
     * @mbggenerated Fri Jan 11 18:01:24 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rentsystem..house
     *
     * @mbggenerated Fri Jan 11 18:01:24 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rentsystem..house
     *
     * @mbggenerated Fri Jan 11 18:01:24 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..house
     *
     * @mbggenerated Fri Jan 11 18:01:24 CST 2019
     */
    public HouseExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..house
     *
     * @mbggenerated Fri Jan 11 18:01:24 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..house
     *
     * @mbggenerated Fri Jan 11 18:01:24 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..house
     *
     * @mbggenerated Fri Jan 11 18:01:24 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..house
     *
     * @mbggenerated Fri Jan 11 18:01:24 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..house
     *
     * @mbggenerated Fri Jan 11 18:01:24 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..house
     *
     * @mbggenerated Fri Jan 11 18:01:24 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..house
     *
     * @mbggenerated Fri Jan 11 18:01:24 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..house
     *
     * @mbggenerated Fri Jan 11 18:01:24 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..house
     *
     * @mbggenerated Fri Jan 11 18:01:24 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..house
     *
     * @mbggenerated Fri Jan 11 18:01:24 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rentsystem..house
     *
     * @mbggenerated Fri Jan 11 18:01:24 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andHouseidIsNull() {
            addCriterion("houseId is null");
            return (Criteria) this;
        }

        public Criteria andHouseidIsNotNull() {
            addCriterion("houseId is not null");
            return (Criteria) this;
        }

        public Criteria andHouseidEqualTo(Integer value) {
            addCriterion("houseId =", value, "houseid");
            return (Criteria) this;
        }

        public Criteria andHouseidNotEqualTo(Integer value) {
            addCriterion("houseId <>", value, "houseid");
            return (Criteria) this;
        }

        public Criteria andHouseidGreaterThan(Integer value) {
            addCriterion("houseId >", value, "houseid");
            return (Criteria) this;
        }

        public Criteria andHouseidGreaterThanOrEqualTo(Integer value) {
            addCriterion("houseId >=", value, "houseid");
            return (Criteria) this;
        }

        public Criteria andHouseidLessThan(Integer value) {
            addCriterion("houseId <", value, "houseid");
            return (Criteria) this;
        }

        public Criteria andHouseidLessThanOrEqualTo(Integer value) {
            addCriterion("houseId <=", value, "houseid");
            return (Criteria) this;
        }

        public Criteria andHouseidIn(List<Integer> values) {
            addCriterion("houseId in", values, "houseid");
            return (Criteria) this;
        }

        public Criteria andHouseidNotIn(List<Integer> values) {
            addCriterion("houseId not in", values, "houseid");
            return (Criteria) this;
        }

        public Criteria andHouseidBetween(Integer value1, Integer value2) {
            addCriterion("houseId between", value1, value2, "houseid");
            return (Criteria) this;
        }

        public Criteria andHouseidNotBetween(Integer value1, Integer value2) {
            addCriterion("houseId not between", value1, value2, "houseid");
            return (Criteria) this;
        }

        public Criteria andPublishuseridIsNull() {
            addCriterion("publishUserId is null");
            return (Criteria) this;
        }

        public Criteria andPublishuseridIsNotNull() {
            addCriterion("publishUserId is not null");
            return (Criteria) this;
        }

        public Criteria andPublishuseridEqualTo(Integer value) {
            addCriterion("publishUserId =", value, "publishuserid");
            return (Criteria) this;
        }

        public Criteria andPublishuseridNotEqualTo(Integer value) {
            addCriterion("publishUserId <>", value, "publishuserid");
            return (Criteria) this;
        }

        public Criteria andPublishuseridGreaterThan(Integer value) {
            addCriterion("publishUserId >", value, "publishuserid");
            return (Criteria) this;
        }

        public Criteria andPublishuseridGreaterThanOrEqualTo(Integer value) {
            addCriterion("publishUserId >=", value, "publishuserid");
            return (Criteria) this;
        }

        public Criteria andPublishuseridLessThan(Integer value) {
            addCriterion("publishUserId <", value, "publishuserid");
            return (Criteria) this;
        }

        public Criteria andPublishuseridLessThanOrEqualTo(Integer value) {
            addCriterion("publishUserId <=", value, "publishuserid");
            return (Criteria) this;
        }

        public Criteria andPublishuseridIn(List<Integer> values) {
            addCriterion("publishUserId in", values, "publishuserid");
            return (Criteria) this;
        }

        public Criteria andPublishuseridNotIn(List<Integer> values) {
            addCriterion("publishUserId not in", values, "publishuserid");
            return (Criteria) this;
        }

        public Criteria andPublishuseridBetween(Integer value1, Integer value2) {
            addCriterion("publishUserId between", value1, value2, "publishuserid");
            return (Criteria) this;
        }

        public Criteria andPublishuseridNotBetween(Integer value1, Integer value2) {
            addCriterion("publishUserId not between", value1, value2, "publishuserid");
            return (Criteria) this;
        }

        public Criteria andCitynameIsNull() {
            addCriterion("cityName is null");
            return (Criteria) this;
        }

        public Criteria andCitynameIsNotNull() {
            addCriterion("cityName is not null");
            return (Criteria) this;
        }

        public Criteria andCitynameEqualTo(String value) {
            addCriterion("cityName =", value, "cityname");
            return (Criteria) this;
        }

        public Criteria andCitynameNotEqualTo(String value) {
            addCriterion("cityName <>", value, "cityname");
            return (Criteria) this;
        }

        public Criteria andCitynameGreaterThan(String value) {
            addCriterion("cityName >", value, "cityname");
            return (Criteria) this;
        }

        public Criteria andCitynameGreaterThanOrEqualTo(String value) {
            addCriterion("cityName >=", value, "cityname");
            return (Criteria) this;
        }

        public Criteria andCitynameLessThan(String value) {
            addCriterion("cityName <", value, "cityname");
            return (Criteria) this;
        }

        public Criteria andCitynameLessThanOrEqualTo(String value) {
            addCriterion("cityName <=", value, "cityname");
            return (Criteria) this;
        }

        public Criteria andCitynameLike(String value) {
            addCriterion("cityName like", value, "cityname");
            return (Criteria) this;
        }

        public Criteria andCitynameNotLike(String value) {
            addCriterion("cityName not like", value, "cityname");
            return (Criteria) this;
        }

        public Criteria andCitynameIn(List<String> values) {
            addCriterion("cityName in", values, "cityname");
            return (Criteria) this;
        }

        public Criteria andCitynameNotIn(List<String> values) {
            addCriterion("cityName not in", values, "cityname");
            return (Criteria) this;
        }

        public Criteria andCitynameBetween(String value1, String value2) {
            addCriterion("cityName between", value1, value2, "cityname");
            return (Criteria) this;
        }

        public Criteria andCitynameNotBetween(String value1, String value2) {
            addCriterion("cityName not between", value1, value2, "cityname");
            return (Criteria) this;
        }

        public Criteria andCommunitynameIsNull() {
            addCriterion("communityName is null");
            return (Criteria) this;
        }

        public Criteria andCommunitynameIsNotNull() {
            addCriterion("communityName is not null");
            return (Criteria) this;
        }

        public Criteria andCommunitynameEqualTo(String value) {
            addCriterion("communityName =", value, "communityname");
            return (Criteria) this;
        }

        public Criteria andCommunitynameNotEqualTo(String value) {
            addCriterion("communityName <>", value, "communityname");
            return (Criteria) this;
        }

        public Criteria andCommunitynameGreaterThan(String value) {
            addCriterion("communityName >", value, "communityname");
            return (Criteria) this;
        }

        public Criteria andCommunitynameGreaterThanOrEqualTo(String value) {
            addCriterion("communityName >=", value, "communityname");
            return (Criteria) this;
        }

        public Criteria andCommunitynameLessThan(String value) {
            addCriterion("communityName <", value, "communityname");
            return (Criteria) this;
        }

        public Criteria andCommunitynameLessThanOrEqualTo(String value) {
            addCriterion("communityName <=", value, "communityname");
            return (Criteria) this;
        }

        public Criteria andCommunitynameLike(String value) {
            addCriterion("communityName like", value, "communityname");
            return (Criteria) this;
        }

        public Criteria andCommunitynameNotLike(String value) {
            addCriterion("communityName not like", value, "communityname");
            return (Criteria) this;
        }

        public Criteria andCommunitynameIn(List<String> values) {
            addCriterion("communityName in", values, "communityname");
            return (Criteria) this;
        }

        public Criteria andCommunitynameNotIn(List<String> values) {
            addCriterion("communityName not in", values, "communityname");
            return (Criteria) this;
        }

        public Criteria andCommunitynameBetween(String value1, String value2) {
            addCriterion("communityName between", value1, value2, "communityname");
            return (Criteria) this;
        }

        public Criteria andCommunitynameNotBetween(String value1, String value2) {
            addCriterion("communityName not between", value1, value2, "communityname");
            return (Criteria) this;
        }

        public Criteria andBuildingnumberIsNull() {
            addCriterion("buildingNumber is null");
            return (Criteria) this;
        }

        public Criteria andBuildingnumberIsNotNull() {
            addCriterion("buildingNumber is not null");
            return (Criteria) this;
        }

        public Criteria andBuildingnumberEqualTo(String value) {
            addCriterion("buildingNumber =", value, "buildingnumber");
            return (Criteria) this;
        }

        public Criteria andBuildingnumberNotEqualTo(String value) {
            addCriterion("buildingNumber <>", value, "buildingnumber");
            return (Criteria) this;
        }

        public Criteria andBuildingnumberGreaterThan(String value) {
            addCriterion("buildingNumber >", value, "buildingnumber");
            return (Criteria) this;
        }

        public Criteria andBuildingnumberGreaterThanOrEqualTo(String value) {
            addCriterion("buildingNumber >=", value, "buildingnumber");
            return (Criteria) this;
        }

        public Criteria andBuildingnumberLessThan(String value) {
            addCriterion("buildingNumber <", value, "buildingnumber");
            return (Criteria) this;
        }

        public Criteria andBuildingnumberLessThanOrEqualTo(String value) {
            addCriterion("buildingNumber <=", value, "buildingnumber");
            return (Criteria) this;
        }

        public Criteria andBuildingnumberLike(String value) {
            addCriterion("buildingNumber like", value, "buildingnumber");
            return (Criteria) this;
        }

        public Criteria andBuildingnumberNotLike(String value) {
            addCriterion("buildingNumber not like", value, "buildingnumber");
            return (Criteria) this;
        }

        public Criteria andBuildingnumberIn(List<String> values) {
            addCriterion("buildingNumber in", values, "buildingnumber");
            return (Criteria) this;
        }

        public Criteria andBuildingnumberNotIn(List<String> values) {
            addCriterion("buildingNumber not in", values, "buildingnumber");
            return (Criteria) this;
        }

        public Criteria andBuildingnumberBetween(String value1, String value2) {
            addCriterion("buildingNumber between", value1, value2, "buildingnumber");
            return (Criteria) this;
        }

        public Criteria andBuildingnumberNotBetween(String value1, String value2) {
            addCriterion("buildingNumber not between", value1, value2, "buildingnumber");
            return (Criteria) this;
        }

        public Criteria andHousetypeIsNull() {
            addCriterion("houseType is null");
            return (Criteria) this;
        }

        public Criteria andHousetypeIsNotNull() {
            addCriterion("houseType is not null");
            return (Criteria) this;
        }

        public Criteria andHousetypeEqualTo(Integer value) {
            addCriterion("houseType =", value, "housetype");
            return (Criteria) this;
        }

        public Criteria andHousetypeNotEqualTo(Integer value) {
            addCriterion("houseType <>", value, "housetype");
            return (Criteria) this;
        }

        public Criteria andHousetypeGreaterThan(Integer value) {
            addCriterion("houseType >", value, "housetype");
            return (Criteria) this;
        }

        public Criteria andHousetypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("houseType >=", value, "housetype");
            return (Criteria) this;
        }

        public Criteria andHousetypeLessThan(Integer value) {
            addCriterion("houseType <", value, "housetype");
            return (Criteria) this;
        }

        public Criteria andHousetypeLessThanOrEqualTo(Integer value) {
            addCriterion("houseType <=", value, "housetype");
            return (Criteria) this;
        }

        public Criteria andHousetypeIn(List<Integer> values) {
            addCriterion("houseType in", values, "housetype");
            return (Criteria) this;
        }

        public Criteria andHousetypeNotIn(List<Integer> values) {
            addCriterion("houseType not in", values, "housetype");
            return (Criteria) this;
        }

        public Criteria andHousetypeBetween(Integer value1, Integer value2) {
            addCriterion("houseType between", value1, value2, "housetype");
            return (Criteria) this;
        }

        public Criteria andHousetypeNotBetween(Integer value1, Integer value2) {
            addCriterion("houseType not between", value1, value2, "housetype");
            return (Criteria) this;
        }

        public Criteria andHouseareaIsNull() {
            addCriterion("houseArea is null");
            return (Criteria) this;
        }

        public Criteria andHouseareaIsNotNull() {
            addCriterion("houseArea is not null");
            return (Criteria) this;
        }

        public Criteria andHouseareaEqualTo(Integer value) {
            addCriterion("houseArea =", value, "housearea");
            return (Criteria) this;
        }

        public Criteria andHouseareaNotEqualTo(Integer value) {
            addCriterion("houseArea <>", value, "housearea");
            return (Criteria) this;
        }

        public Criteria andHouseareaGreaterThan(Integer value) {
            addCriterion("houseArea >", value, "housearea");
            return (Criteria) this;
        }

        public Criteria andHouseareaGreaterThanOrEqualTo(Integer value) {
            addCriterion("houseArea >=", value, "housearea");
            return (Criteria) this;
        }

        public Criteria andHouseareaLessThan(Integer value) {
            addCriterion("houseArea <", value, "housearea");
            return (Criteria) this;
        }

        public Criteria andHouseareaLessThanOrEqualTo(Integer value) {
            addCriterion("houseArea <=", value, "housearea");
            return (Criteria) this;
        }

        public Criteria andHouseareaIn(List<Integer> values) {
            addCriterion("houseArea in", values, "housearea");
            return (Criteria) this;
        }

        public Criteria andHouseareaNotIn(List<Integer> values) {
            addCriterion("houseArea not in", values, "housearea");
            return (Criteria) this;
        }

        public Criteria andHouseareaBetween(Integer value1, Integer value2) {
            addCriterion("houseArea between", value1, value2, "housearea");
            return (Criteria) this;
        }

        public Criteria andHouseareaNotBetween(Integer value1, Integer value2) {
            addCriterion("houseArea not between", value1, value2, "housearea");
            return (Criteria) this;
        }

        public Criteria andFloornumberIsNull() {
            addCriterion("floorNumber is null");
            return (Criteria) this;
        }

        public Criteria andFloornumberIsNotNull() {
            addCriterion("floorNumber is not null");
            return (Criteria) this;
        }

        public Criteria andFloornumberEqualTo(Integer value) {
            addCriterion("floorNumber =", value, "floornumber");
            return (Criteria) this;
        }

        public Criteria andFloornumberNotEqualTo(Integer value) {
            addCriterion("floorNumber <>", value, "floornumber");
            return (Criteria) this;
        }

        public Criteria andFloornumberGreaterThan(Integer value) {
            addCriterion("floorNumber >", value, "floornumber");
            return (Criteria) this;
        }

        public Criteria andFloornumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("floorNumber >=", value, "floornumber");
            return (Criteria) this;
        }

        public Criteria andFloornumberLessThan(Integer value) {
            addCriterion("floorNumber <", value, "floornumber");
            return (Criteria) this;
        }

        public Criteria andFloornumberLessThanOrEqualTo(Integer value) {
            addCriterion("floorNumber <=", value, "floornumber");
            return (Criteria) this;
        }

        public Criteria andFloornumberIn(List<Integer> values) {
            addCriterion("floorNumber in", values, "floornumber");
            return (Criteria) this;
        }

        public Criteria andFloornumberNotIn(List<Integer> values) {
            addCriterion("floorNumber not in", values, "floornumber");
            return (Criteria) this;
        }

        public Criteria andFloornumberBetween(Integer value1, Integer value2) {
            addCriterion("floorNumber between", value1, value2, "floornumber");
            return (Criteria) this;
        }

        public Criteria andFloornumberNotBetween(Integer value1, Integer value2) {
            addCriterion("floorNumber not between", value1, value2, "floornumber");
            return (Criteria) this;
        }

        public Criteria andElevatorornotIsNull() {
            addCriterion("elevatorOrNot is null");
            return (Criteria) this;
        }

        public Criteria andElevatorornotIsNotNull() {
            addCriterion("elevatorOrNot is not null");
            return (Criteria) this;
        }

        public Criteria andElevatorornotEqualTo(Integer value) {
            addCriterion("elevatorOrNot =", value, "elevatorornot");
            return (Criteria) this;
        }

        public Criteria andElevatorornotNotEqualTo(Integer value) {
            addCriterion("elevatorOrNot <>", value, "elevatorornot");
            return (Criteria) this;
        }

        public Criteria andElevatorornotGreaterThan(Integer value) {
            addCriterion("elevatorOrNot >", value, "elevatorornot");
            return (Criteria) this;
        }

        public Criteria andElevatorornotGreaterThanOrEqualTo(Integer value) {
            addCriterion("elevatorOrNot >=", value, "elevatorornot");
            return (Criteria) this;
        }

        public Criteria andElevatorornotLessThan(Integer value) {
            addCriterion("elevatorOrNot <", value, "elevatorornot");
            return (Criteria) this;
        }

        public Criteria andElevatorornotLessThanOrEqualTo(Integer value) {
            addCriterion("elevatorOrNot <=", value, "elevatorornot");
            return (Criteria) this;
        }

        public Criteria andElevatorornotIn(List<Integer> values) {
            addCriterion("elevatorOrNot in", values, "elevatorornot");
            return (Criteria) this;
        }

        public Criteria andElevatorornotNotIn(List<Integer> values) {
            addCriterion("elevatorOrNot not in", values, "elevatorornot");
            return (Criteria) this;
        }

        public Criteria andElevatorornotBetween(Integer value1, Integer value2) {
            addCriterion("elevatorOrNot between", value1, value2, "elevatorornot");
            return (Criteria) this;
        }

        public Criteria andElevatorornotNotBetween(Integer value1, Integer value2) {
            addCriterion("elevatorOrNot not between", value1, value2, "elevatorornot");
            return (Criteria) this;
        }

        public Criteria andHousedescriptionIsNull() {
            addCriterion("houseDescription is null");
            return (Criteria) this;
        }

        public Criteria andHousedescriptionIsNotNull() {
            addCriterion("houseDescription is not null");
            return (Criteria) this;
        }

        public Criteria andHousedescriptionEqualTo(String value) {
            addCriterion("houseDescription =", value, "housedescription");
            return (Criteria) this;
        }

        public Criteria andHousedescriptionNotEqualTo(String value) {
            addCriterion("houseDescription <>", value, "housedescription");
            return (Criteria) this;
        }

        public Criteria andHousedescriptionGreaterThan(String value) {
            addCriterion("houseDescription >", value, "housedescription");
            return (Criteria) this;
        }

        public Criteria andHousedescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("houseDescription >=", value, "housedescription");
            return (Criteria) this;
        }

        public Criteria andHousedescriptionLessThan(String value) {
            addCriterion("houseDescription <", value, "housedescription");
            return (Criteria) this;
        }

        public Criteria andHousedescriptionLessThanOrEqualTo(String value) {
            addCriterion("houseDescription <=", value, "housedescription");
            return (Criteria) this;
        }

        public Criteria andHousedescriptionLike(String value) {
            addCriterion("houseDescription like", value, "housedescription");
            return (Criteria) this;
        }

        public Criteria andHousedescriptionNotLike(String value) {
            addCriterion("houseDescription not like", value, "housedescription");
            return (Criteria) this;
        }

        public Criteria andHousedescriptionIn(List<String> values) {
            addCriterion("houseDescription in", values, "housedescription");
            return (Criteria) this;
        }

        public Criteria andHousedescriptionNotIn(List<String> values) {
            addCriterion("houseDescription not in", values, "housedescription");
            return (Criteria) this;
        }

        public Criteria andHousedescriptionBetween(String value1, String value2) {
            addCriterion("houseDescription between", value1, value2, "housedescription");
            return (Criteria) this;
        }

        public Criteria andHousedescriptionNotBetween(String value1, String value2) {
            addCriterion("houseDescription not between", value1, value2, "housedescription");
            return (Criteria) this;
        }

        public Criteria andPhotonumIsNull() {
            addCriterion("photoNum is null");
            return (Criteria) this;
        }

        public Criteria andPhotonumIsNotNull() {
            addCriterion("photoNum is not null");
            return (Criteria) this;
        }

        public Criteria andPhotonumEqualTo(Integer value) {
            addCriterion("photoNum =", value, "photonum");
            return (Criteria) this;
        }

        public Criteria andPhotonumNotEqualTo(Integer value) {
            addCriterion("photoNum <>", value, "photonum");
            return (Criteria) this;
        }

        public Criteria andPhotonumGreaterThan(Integer value) {
            addCriterion("photoNum >", value, "photonum");
            return (Criteria) this;
        }

        public Criteria andPhotonumGreaterThanOrEqualTo(Integer value) {
            addCriterion("photoNum >=", value, "photonum");
            return (Criteria) this;
        }

        public Criteria andPhotonumLessThan(Integer value) {
            addCriterion("photoNum <", value, "photonum");
            return (Criteria) this;
        }

        public Criteria andPhotonumLessThanOrEqualTo(Integer value) {
            addCriterion("photoNum <=", value, "photonum");
            return (Criteria) this;
        }

        public Criteria andPhotonumIn(List<Integer> values) {
            addCriterion("photoNum in", values, "photonum");
            return (Criteria) this;
        }

        public Criteria andPhotonumNotIn(List<Integer> values) {
            addCriterion("photoNum not in", values, "photonum");
            return (Criteria) this;
        }

        public Criteria andPhotonumBetween(Integer value1, Integer value2) {
            addCriterion("photoNum between", value1, value2, "photonum");
            return (Criteria) this;
        }

        public Criteria andPhotonumNotBetween(Integer value1, Integer value2) {
            addCriterion("photoNum not between", value1, value2, "photonum");
            return (Criteria) this;
        }

        public Criteria andDepositmoneyIsNull() {
            addCriterion("depositMoney is null");
            return (Criteria) this;
        }

        public Criteria andDepositmoneyIsNotNull() {
            addCriterion("depositMoney is not null");
            return (Criteria) this;
        }

        public Criteria andDepositmoneyEqualTo(Float value) {
            addCriterion("depositMoney =", value, "depositmoney");
            return (Criteria) this;
        }

        public Criteria andDepositmoneyNotEqualTo(Float value) {
            addCriterion("depositMoney <>", value, "depositmoney");
            return (Criteria) this;
        }

        public Criteria andDepositmoneyGreaterThan(Float value) {
            addCriterion("depositMoney >", value, "depositmoney");
            return (Criteria) this;
        }

        public Criteria andDepositmoneyGreaterThanOrEqualTo(Float value) {
            addCriterion("depositMoney >=", value, "depositmoney");
            return (Criteria) this;
        }

        public Criteria andDepositmoneyLessThan(Float value) {
            addCriterion("depositMoney <", value, "depositmoney");
            return (Criteria) this;
        }

        public Criteria andDepositmoneyLessThanOrEqualTo(Float value) {
            addCriterion("depositMoney <=", value, "depositmoney");
            return (Criteria) this;
        }

        public Criteria andDepositmoneyIn(List<Float> values) {
            addCriterion("depositMoney in", values, "depositmoney");
            return (Criteria) this;
        }

        public Criteria andDepositmoneyNotIn(List<Float> values) {
            addCriterion("depositMoney not in", values, "depositmoney");
            return (Criteria) this;
        }

        public Criteria andDepositmoneyBetween(Float value1, Float value2) {
            addCriterion("depositMoney between", value1, value2, "depositmoney");
            return (Criteria) this;
        }

        public Criteria andDepositmoneyNotBetween(Float value1, Float value2) {
            addCriterion("depositMoney not between", value1, value2, "depositmoney");
            return (Criteria) this;
        }

        public Criteria andPaymentmethodIsNull() {
            addCriterion("paymentMethod is null");
            return (Criteria) this;
        }

        public Criteria andPaymentmethodIsNotNull() {
            addCriterion("paymentMethod is not null");
            return (Criteria) this;
        }

        public Criteria andPaymentmethodEqualTo(Integer value) {
            addCriterion("paymentMethod =", value, "paymentmethod");
            return (Criteria) this;
        }

        public Criteria andPaymentmethodNotEqualTo(Integer value) {
            addCriterion("paymentMethod <>", value, "paymentmethod");
            return (Criteria) this;
        }

        public Criteria andPaymentmethodGreaterThan(Integer value) {
            addCriterion("paymentMethod >", value, "paymentmethod");
            return (Criteria) this;
        }

        public Criteria andPaymentmethodGreaterThanOrEqualTo(Integer value) {
            addCriterion("paymentMethod >=", value, "paymentmethod");
            return (Criteria) this;
        }

        public Criteria andPaymentmethodLessThan(Integer value) {
            addCriterion("paymentMethod <", value, "paymentmethod");
            return (Criteria) this;
        }

        public Criteria andPaymentmethodLessThanOrEqualTo(Integer value) {
            addCriterion("paymentMethod <=", value, "paymentmethod");
            return (Criteria) this;
        }

        public Criteria andPaymentmethodIn(List<Integer> values) {
            addCriterion("paymentMethod in", values, "paymentmethod");
            return (Criteria) this;
        }

        public Criteria andPaymentmethodNotIn(List<Integer> values) {
            addCriterion("paymentMethod not in", values, "paymentmethod");
            return (Criteria) this;
        }

        public Criteria andPaymentmethodBetween(Integer value1, Integer value2) {
            addCriterion("paymentMethod between", value1, value2, "paymentmethod");
            return (Criteria) this;
        }

        public Criteria andPaymentmethodNotBetween(Integer value1, Integer value2) {
            addCriterion("paymentMethod not between", value1, value2, "paymentmethod");
            return (Criteria) this;
        }

        public Criteria andRentmoneyIsNull() {
            addCriterion("rentMoney is null");
            return (Criteria) this;
        }

        public Criteria andRentmoneyIsNotNull() {
            addCriterion("rentMoney is not null");
            return (Criteria) this;
        }

        public Criteria andRentmoneyEqualTo(Float value) {
            addCriterion("rentMoney =", value, "rentmoney");
            return (Criteria) this;
        }

        public Criteria andRentmoneyNotEqualTo(Float value) {
            addCriterion("rentMoney <>", value, "rentmoney");
            return (Criteria) this;
        }

        public Criteria andRentmoneyGreaterThan(Float value) {
            addCriterion("rentMoney >", value, "rentmoney");
            return (Criteria) this;
        }

        public Criteria andRentmoneyGreaterThanOrEqualTo(Float value) {
            addCriterion("rentMoney >=", value, "rentmoney");
            return (Criteria) this;
        }

        public Criteria andRentmoneyLessThan(Float value) {
            addCriterion("rentMoney <", value, "rentmoney");
            return (Criteria) this;
        }

        public Criteria andRentmoneyLessThanOrEqualTo(Float value) {
            addCriterion("rentMoney <=", value, "rentmoney");
            return (Criteria) this;
        }

        public Criteria andRentmoneyIn(List<Float> values) {
            addCriterion("rentMoney in", values, "rentmoney");
            return (Criteria) this;
        }

        public Criteria andRentmoneyNotIn(List<Float> values) {
            addCriterion("rentMoney not in", values, "rentmoney");
            return (Criteria) this;
        }

        public Criteria andRentmoneyBetween(double value1, double value2) {
            addCriterion("rentMoney between", value1, value2, "rentmoney");
            return (Criteria) this;
        }

        public Criteria andRentmoneyNotBetween(Float value1, Float value2) {
            addCriterion("rentMoney not between", value1, value2, "rentmoney");
            return (Criteria) this;
        }

        public Criteria andRegisttimeIsNull() {
            addCriterion("registTime is null");
            return (Criteria) this;
        }

        public Criteria andRegisttimeIsNotNull() {
            addCriterion("registTime is not null");
            return (Criteria) this;
        }

        public Criteria andRegisttimeEqualTo(String value) {
            addCriterion("registTime =", value, "registtime");
            return (Criteria) this;
        }

        public Criteria andRegisttimeNotEqualTo(String value) {
            addCriterion("registTime <>", value, "registtime");
            return (Criteria) this;
        }

        public Criteria andRegisttimeGreaterThan(String value) {
            addCriterion("registTime >", value, "registtime");
            return (Criteria) this;
        }

        public Criteria andRegisttimeGreaterThanOrEqualTo(String value) {
            addCriterion("registTime >=", value, "registtime");
            return (Criteria) this;
        }

        public Criteria andRegisttimeLessThan(String value) {
            addCriterion("registTime <", value, "registtime");
            return (Criteria) this;
        }

        public Criteria andRegisttimeLessThanOrEqualTo(String value) {
            addCriterion("registTime <=", value, "registtime");
            return (Criteria) this;
        }

        public Criteria andRegisttimeLike(String value) {
            addCriterion("registTime like", value, "registtime");
            return (Criteria) this;
        }

        public Criteria andRegisttimeNotLike(String value) {
            addCriterion("registTime not like", value, "registtime");
            return (Criteria) this;
        }

        public Criteria andRegisttimeIn(List<String> values) {
            addCriterion("registTime in", values, "registtime");
            return (Criteria) this;
        }

        public Criteria andRegisttimeNotIn(List<String> values) {
            addCriterion("registTime not in", values, "registtime");
            return (Criteria) this;
        }

        public Criteria andRegisttimeBetween(String value1, String value2) {
            addCriterion("registTime between", value1, value2, "registtime");
            return (Criteria) this;
        }

        public Criteria andRegisttimeNotBetween(String value1, String value2) {
            addCriterion("registTime not between", value1, value2, "registtime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNull() {
            addCriterion("updateTime is null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNotNull() {
            addCriterion("updateTime is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeEqualTo(String value) {
            addCriterion("updateTime =", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotEqualTo(String value) {
            addCriterion("updateTime <>", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThan(String value) {
            addCriterion("updateTime >", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThanOrEqualTo(String value) {
            addCriterion("updateTime >=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThan(String value) {
            addCriterion("updateTime <", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThanOrEqualTo(String value) {
            addCriterion("updateTime <=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLike(String value) {
            addCriterion("updateTime like", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotLike(String value) {
            addCriterion("updateTime not like", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIn(List<String> values) {
            addCriterion("updateTime in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotIn(List<String> values) {
            addCriterion("updateTime not in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeBetween(String value1, String value2) {
            addCriterion("updateTime between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotBetween(String value1, String value2) {
            addCriterion("updateTime not between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andHousestatusIsNull() {
            addCriterion("houseStatus is null");
            return (Criteria) this;
        }

        public Criteria andHousestatusIsNotNull() {
            addCriterion("houseStatus is not null");
            return (Criteria) this;
        }

        public Criteria andHousestatusEqualTo(Integer value) {
            addCriterion("houseStatus =", value, "housestatus");
            return (Criteria) this;
        }

        public Criteria andHousestatusNotEqualTo(Integer value) {
            addCriterion("houseStatus <>", value, "housestatus");
            return (Criteria) this;
        }

        public Criteria andHousestatusGreaterThan(Integer value) {
            addCriterion("houseStatus >", value, "housestatus");
            return (Criteria) this;
        }

        public Criteria andHousestatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("houseStatus >=", value, "housestatus");
            return (Criteria) this;
        }

        public Criteria andHousestatusLessThan(Integer value) {
            addCriterion("houseStatus <", value, "housestatus");
            return (Criteria) this;
        }

        public Criteria andHousestatusLessThanOrEqualTo(Integer value) {
            addCriterion("houseStatus <=", value, "housestatus");
            return (Criteria) this;
        }

        public Criteria andHousestatusIn(List<Integer> values) {
            addCriterion("houseStatus in", values, "housestatus");
            return (Criteria) this;
        }

        public Criteria andHousestatusNotIn(List<Integer> values) {
            addCriterion("houseStatus not in", values, "housestatus");
            return (Criteria) this;
        }

        public Criteria andHousestatusBetween(Integer value1, Integer value2) {
            addCriterion("houseStatus between", value1, value2, "housestatus");
            return (Criteria) this;
        }

        public Criteria andHousestatusNotBetween(Integer value1, Integer value2) {
            addCriterion("houseStatus not between", value1, value2, "housestatus");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rentsystem..house
     *
     * @mbggenerated do_not_delete_during_merge Fri Jan 11 18:01:24 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rentsystem..house
     *
     * @mbggenerated Fri Jan 11 18:01:24 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}