package com.rent.entity;

public class House {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rentsystem..house.houseId
     *
     * @mbggenerated Tue Dec 25 11:22:31 CST 2018
     */
    private Integer houseid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rentsystem..house.publishUserId
     *
     * @mbggenerated Tue Dec 25 11:22:31 CST 2018
     */
    private Integer publishuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rentsystem..house.cityName
     *
     * @mbggenerated Tue Dec 25 11:22:31 CST 2018
     */
    private String cityname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rentsystem..house.communityName
     *
     * @mbggenerated Tue Dec 25 11:22:31 CST 2018
     */
    private String communityname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rentsystem..house.buildingNumber
     *
     * @mbggenerated Tue Dec 25 11:22:31 CST 2018
     */
    private String buildingnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rentsystem..house.houseType
     *
     * @mbggenerated Tue Dec 25 11:22:31 CST 2018
     */
    private Integer housetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rentsystem..house.houseArea
     *
     * @mbggenerated Tue Dec 25 11:22:31 CST 2018
     */
    private Integer housearea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rentsystem..house.floorNumber
     *
     * @mbggenerated Tue Dec 25 11:22:31 CST 2018
     */
    private Integer floornumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rentsystem..house.elevatorOrNot
     *
     * @mbggenerated Tue Dec 25 11:22:31 CST 2018
     */
    private Integer elevatorornot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rentsystem..house.houseDescription
     *
     * @mbggenerated Tue Dec 25 11:22:31 CST 2018
     */
    private String housedescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rentsystem..house.housePhoto
     *
     * @mbggenerated Tue Dec 25 11:22:31 CST 2018
     */
    private String housephoto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rentsystem..house.deposit
     *
     * @mbggenerated Tue Dec 25 11:22:31 CST 2018
     */
    private Float deposit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rentsystem..house.paymentMethod
     *
     * @mbggenerated Tue Dec 25 11:22:31 CST 2018
     */
    private Integer paymentmethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rentsystem..house.rent
     *
     * @mbggenerated Tue Dec 25 11:22:31 CST 2018
     */
    private Float rent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rentsystem..house.registTime
     *
     * @mbggenerated Tue Dec 25 11:22:31 CST 2018
     */
    private String registtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rentsystem..house.updateTime
     *
     * @mbggenerated Tue Dec 25 11:22:31 CST 2018
     */
    private String updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rentsystem..house.housestatus
     *
     * @mbggenerated Tue Dec 25 11:22:31 CST 2018
     */
    private Integer housestatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rentsystem..house.houseId
     *
     * @return the value of rentsystem..house.houseId
     *
     * @mbggenerated Tue Dec 25 11:22:31 CST 2018
     */
    public Integer getHouseid() {
        return houseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rentsystem..house.houseId
     *
     * @param houseid the value for rentsystem..house.houseId
     *
     * @mbggenerated Tue Dec 25 11:22:31 CST 2018
     */
    public void setHouseid(Integer houseid) {
        this.houseid = houseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rentsystem..house.publishUserId
     *
     * @return the value of rentsystem..house.publishUserId
     *
     * @mbggenerated Tue Dec 25 11:22:31 CST 2018
     */
    public Integer getPublishuserid() {
        return publishuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rentsystem..house.publishUserId
     *
     * @param publishuserid the value for rentsystem..house.publishUserId
     *
     * @mbggenerated Tue Dec 25 11:22:31 CST 2018
     */
    public void setPublishuserid(Integer publishuserid) {
        this.publishuserid = publishuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rentsystem..house.cityName
     *
     * @return the value of rentsystem..house.cityName
     *
     * @mbggenerated Tue Dec 25 11:22:31 CST 2018
     */
    public String getCityname() {
        return cityname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rentsystem..house.cityName
     *
     * @param cityname the value for rentsystem..house.cityName
     *
     * @mbggenerated Tue Dec 25 11:22:31 CST 2018
     */
    public void setCityname(String cityname) {
        this.cityname = cityname == null ? null : cityname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rentsystem..house.communityName
     *
     * @return the value of rentsystem..house.communityName
     *
     * @mbggenerated Tue Dec 25 11:22:31 CST 2018
     */
    public String getCommunityname() {
        return communityname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rentsystem..house.communityName
     *
     * @param communityname the value for rentsystem..house.communityName
     *
     * @mbggenerated Tue Dec 25 11:22:31 CST 2018
     */
    public void setCommunityname(String communityname) {
        this.communityname = communityname == null ? null : communityname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rentsystem..house.buildingNumber
     *
     * @return the value of rentsystem..house.buildingNumber
     *
     * @mbggenerated Tue Dec 25 11:22:31 CST 2018
     */
    public String getBuildingnumber() {
        return buildingnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rentsystem..house.buildingNumber
     *
     * @param buildingnumber the value for rentsystem..house.buildingNumber
     *
     * @mbggenerated Tue Dec 25 11:22:31 CST 2018
     */
    public void setBuildingnumber(String buildingnumber) {
        this.buildingnumber = buildingnumber == null ? null : buildingnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rentsystem..house.houseType
     *
     * @return the value of rentsystem..house.houseType
     *
     * @mbggenerated Tue Dec 25 11:22:31 CST 2018
     */
    public Integer getHousetype() {
        return housetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rentsystem..house.houseType
     *
     * @param housetype the value for rentsystem..house.houseType
     *
     * @mbggenerated Tue Dec 25 11:22:31 CST 2018
     */
    public void setHousetype(Integer housetype) {
        this.housetype = housetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rentsystem..house.houseArea
     *
     * @return the value of rentsystem..house.houseArea
     *
     * @mbggenerated Tue Dec 25 11:22:31 CST 2018
     */
    public Integer getHousearea() {
        return housearea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rentsystem..house.houseArea
     *
     * @param housearea the value for rentsystem..house.houseArea
     *
     * @mbggenerated Tue Dec 25 11:22:31 CST 2018
     */
    public void setHousearea(Integer housearea) {
        this.housearea = housearea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rentsystem..house.floorNumber
     *
     * @return the value of rentsystem..house.floorNumber
     *
     * @mbggenerated Tue Dec 25 11:22:31 CST 2018
     */
    public Integer getFloornumber() {
        return floornumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rentsystem..house.floorNumber
     *
     * @param floornumber the value for rentsystem..house.floorNumber
     *
     * @mbggenerated Tue Dec 25 11:22:31 CST 2018
     */
    public void setFloornumber(Integer floornumber) {
        this.floornumber = floornumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rentsystem..house.elevatorOrNot
     *
     * @return the value of rentsystem..house.elevatorOrNot
     *
     * @mbggenerated Tue Dec 25 11:22:31 CST 2018
     */
    public Integer getElevatorornot() {
        return elevatorornot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rentsystem..house.elevatorOrNot
     *
     * @param elevatorornot the value for rentsystem..house.elevatorOrNot
     *
     * @mbggenerated Tue Dec 25 11:22:31 CST 2018
     */
    public void setElevatorornot(Integer elevatorornot) {
        this.elevatorornot = elevatorornot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rentsystem..house.houseDescription
     *
     * @return the value of rentsystem..house.houseDescription
     *
     * @mbggenerated Tue Dec 25 11:22:31 CST 2018
     */
    public String getHousedescription() {
        return housedescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rentsystem..house.houseDescription
     *
     * @param housedescription the value for rentsystem..house.houseDescription
     *
     * @mbggenerated Tue Dec 25 11:22:31 CST 2018
     */
    public void setHousedescription(String housedescription) {
        this.housedescription = housedescription == null ? null : housedescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rentsystem..house.housePhoto
     *
     * @return the value of rentsystem..house.housePhoto
     *
     * @mbggenerated Tue Dec 25 11:22:31 CST 2018
     */
    public String getHousephoto() {
        return housephoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rentsystem..house.housePhoto
     *
     * @param housephoto the value for rentsystem..house.housePhoto
     *
     * @mbggenerated Tue Dec 25 11:22:31 CST 2018
     */
    public void setHousephoto(String housephoto) {
        this.housephoto = housephoto == null ? null : housephoto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rentsystem..house.deposit
     *
     * @return the value of rentsystem..house.deposit
     *
     * @mbggenerated Tue Dec 25 11:22:31 CST 2018
     */
    public Float getDeposit() {
        return deposit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rentsystem..house.deposit
     *
     * @param deposit the value for rentsystem..house.deposit
     *
     * @mbggenerated Tue Dec 25 11:22:31 CST 2018
     */
    public void setDeposit(Float deposit) {
        this.deposit = deposit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rentsystem..house.paymentMethod
     *
     * @return the value of rentsystem..house.paymentMethod
     *
     * @mbggenerated Tue Dec 25 11:22:31 CST 2018
     */
    public Integer getPaymentmethod() {
        return paymentmethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rentsystem..house.paymentMethod
     *
     * @param paymentmethod the value for rentsystem..house.paymentMethod
     *
     * @mbggenerated Tue Dec 25 11:22:31 CST 2018
     */
    public void setPaymentmethod(Integer paymentmethod) {
        this.paymentmethod = paymentmethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rentsystem..house.rent
     *
     * @return the value of rentsystem..house.rent
     *
     * @mbggenerated Tue Dec 25 11:22:31 CST 2018
     */
    public Float getRent() {
        return rent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rentsystem..house.rent
     *
     * @param rent the value for rentsystem..house.rent
     *
     * @mbggenerated Tue Dec 25 11:22:31 CST 2018
     */
    public void setRent(Float rent) {
        this.rent = rent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rentsystem..house.registTime
     *
     * @return the value of rentsystem..house.registTime
     *
     * @mbggenerated Tue Dec 25 11:22:31 CST 2018
     */
    public String getRegisttime() {
        return registtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rentsystem..house.registTime
     *
     * @param registtime the value for rentsystem..house.registTime
     *
     * @mbggenerated Tue Dec 25 11:22:31 CST 2018
     */
    public void setRegisttime(String registtime) {
        this.registtime = registtime == null ? null : registtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rentsystem..house.updateTime
     *
     * @return the value of rentsystem..house.updateTime
     *
     * @mbggenerated Tue Dec 25 11:22:31 CST 2018
     */
    public String getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rentsystem..house.updateTime
     *
     * @param updatetime the value for rentsystem..house.updateTime
     *
     * @mbggenerated Tue Dec 25 11:22:31 CST 2018
     */
    public void setUpdatetime(String updatetime) {
        this.updatetime = updatetime == null ? null : updatetime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rentsystem..house.housestatus
     *
     * @return the value of rentsystem..house.housestatus
     *
     * @mbggenerated Tue Dec 25 11:22:31 CST 2018
     */
    public Integer getHousestatus() {
        return housestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rentsystem..house.housestatus
     *
     * @param housestatus the value for rentsystem..house.housestatus
     *
     * @mbggenerated Tue Dec 25 11:22:31 CST 2018
     */
    public void setHousestatus(Integer housestatus) {
        this.housestatus = housestatus;
    }
}