package com.rent.entity;

import java.util.ArrayList;
import java.util.List;

public class RentTransactionExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rentsystem..renttransaction
     *
     * @mbggenerated Sat Jan 05 21:07:16 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rentsystem..renttransaction
     *
     * @mbggenerated Sat Jan 05 21:07:16 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rentsystem..renttransaction
     *
     * @mbggenerated Sat Jan 05 21:07:16 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..renttransaction
     *
     * @mbggenerated Sat Jan 05 21:07:16 CST 2019
     */
    public RentTransactionExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..renttransaction
     *
     * @mbggenerated Sat Jan 05 21:07:16 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..renttransaction
     *
     * @mbggenerated Sat Jan 05 21:07:16 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..renttransaction
     *
     * @mbggenerated Sat Jan 05 21:07:16 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..renttransaction
     *
     * @mbggenerated Sat Jan 05 21:07:16 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..renttransaction
     *
     * @mbggenerated Sat Jan 05 21:07:16 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..renttransaction
     *
     * @mbggenerated Sat Jan 05 21:07:16 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..renttransaction
     *
     * @mbggenerated Sat Jan 05 21:07:16 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..renttransaction
     *
     * @mbggenerated Sat Jan 05 21:07:16 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..renttransaction
     *
     * @mbggenerated Sat Jan 05 21:07:16 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..renttransaction
     *
     * @mbggenerated Sat Jan 05 21:07:16 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rentsystem..renttransaction
     *
     * @mbggenerated Sat Jan 05 21:07:16 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTransactionidIsNull() {
            addCriterion("transactionId is null");
            return (Criteria) this;
        }

        public Criteria andTransactionidIsNotNull() {
            addCriterion("transactionId is not null");
            return (Criteria) this;
        }

        public Criteria andTransactionidEqualTo(Integer value) {
            addCriterion("transactionId =", value, "transactionid");
            return (Criteria) this;
        }

        public Criteria andTransactionidNotEqualTo(Integer value) {
            addCriterion("transactionId <>", value, "transactionid");
            return (Criteria) this;
        }

        public Criteria andTransactionidGreaterThan(Integer value) {
            addCriterion("transactionId >", value, "transactionid");
            return (Criteria) this;
        }

        public Criteria andTransactionidGreaterThanOrEqualTo(Integer value) {
            addCriterion("transactionId >=", value, "transactionid");
            return (Criteria) this;
        }

        public Criteria andTransactionidLessThan(Integer value) {
            addCriterion("transactionId <", value, "transactionid");
            return (Criteria) this;
        }

        public Criteria andTransactionidLessThanOrEqualTo(Integer value) {
            addCriterion("transactionId <=", value, "transactionid");
            return (Criteria) this;
        }

        public Criteria andTransactionidIn(List<Integer> values) {
            addCriterion("transactionId in", values, "transactionid");
            return (Criteria) this;
        }

        public Criteria andTransactionidNotIn(List<Integer> values) {
            addCriterion("transactionId not in", values, "transactionid");
            return (Criteria) this;
        }

        public Criteria andTransactionidBetween(Integer value1, Integer value2) {
            addCriterion("transactionId between", value1, value2, "transactionid");
            return (Criteria) this;
        }

        public Criteria andTransactionidNotBetween(Integer value1, Integer value2) {
            addCriterion("transactionId not between", value1, value2, "transactionid");
            return (Criteria) this;
        }

        public Criteria andHouseidIsNull() {
            addCriterion("houseId is null");
            return (Criteria) this;
        }

        public Criteria andHouseidIsNotNull() {
            addCriterion("houseId is not null");
            return (Criteria) this;
        }

        public Criteria andHouseidEqualTo(Integer value) {
            addCriterion("houseId =", value, "houseid");
            return (Criteria) this;
        }

        public Criteria andHouseidNotEqualTo(Integer value) {
            addCriterion("houseId <>", value, "houseid");
            return (Criteria) this;
        }

        public Criteria andHouseidGreaterThan(Integer value) {
            addCriterion("houseId >", value, "houseid");
            return (Criteria) this;
        }

        public Criteria andHouseidGreaterThanOrEqualTo(Integer value) {
            addCriterion("houseId >=", value, "houseid");
            return (Criteria) this;
        }

        public Criteria andHouseidLessThan(Integer value) {
            addCriterion("houseId <", value, "houseid");
            return (Criteria) this;
        }

        public Criteria andHouseidLessThanOrEqualTo(Integer value) {
            addCriterion("houseId <=", value, "houseid");
            return (Criteria) this;
        }

        public Criteria andHouseidIn(List<Integer> values) {
            addCriterion("houseId in", values, "houseid");
            return (Criteria) this;
        }

        public Criteria andHouseidNotIn(List<Integer> values) {
            addCriterion("houseId not in", values, "houseid");
            return (Criteria) this;
        }

        public Criteria andHouseidBetween(Integer value1, Integer value2) {
            addCriterion("houseId between", value1, value2, "houseid");
            return (Criteria) this;
        }

        public Criteria andHouseidNotBetween(Integer value1, Integer value2) {
            addCriterion("houseId not between", value1, value2, "houseid");
            return (Criteria) this;
        }

        public Criteria andLandlordidIsNull() {
            addCriterion("landlordId is null");
            return (Criteria) this;
        }

        public Criteria andLandlordidIsNotNull() {
            addCriterion("landlordId is not null");
            return (Criteria) this;
        }

        public Criteria andLandlordidEqualTo(Integer value) {
            addCriterion("landlordId =", value, "landlordid");
            return (Criteria) this;
        }

        public Criteria andLandlordidNotEqualTo(Integer value) {
            addCriterion("landlordId <>", value, "landlordid");
            return (Criteria) this;
        }

        public Criteria andLandlordidGreaterThan(Integer value) {
            addCriterion("landlordId >", value, "landlordid");
            return (Criteria) this;
        }

        public Criteria andLandlordidGreaterThanOrEqualTo(Integer value) {
            addCriterion("landlordId >=", value, "landlordid");
            return (Criteria) this;
        }

        public Criteria andLandlordidLessThan(Integer value) {
            addCriterion("landlordId <", value, "landlordid");
            return (Criteria) this;
        }

        public Criteria andLandlordidLessThanOrEqualTo(Integer value) {
            addCriterion("landlordId <=", value, "landlordid");
            return (Criteria) this;
        }

        public Criteria andLandlordidIn(List<Integer> values) {
            addCriterion("landlordId in", values, "landlordid");
            return (Criteria) this;
        }

        public Criteria andLandlordidNotIn(List<Integer> values) {
            addCriterion("landlordId not in", values, "landlordid");
            return (Criteria) this;
        }

        public Criteria andLandlordidBetween(Integer value1, Integer value2) {
            addCriterion("landlordId between", value1, value2, "landlordid");
            return (Criteria) this;
        }

        public Criteria andLandlordidNotBetween(Integer value1, Integer value2) {
            addCriterion("landlordId not between", value1, value2, "landlordid");
            return (Criteria) this;
        }

        public Criteria andTenantidIsNull() {
            addCriterion("tenantId is null");
            return (Criteria) this;
        }

        public Criteria andTenantidIsNotNull() {
            addCriterion("tenantId is not null");
            return (Criteria) this;
        }

        public Criteria andTenantidEqualTo(Integer value) {
            addCriterion("tenantId =", value, "tenantid");
            return (Criteria) this;
        }

        public Criteria andTenantidNotEqualTo(Integer value) {
            addCriterion("tenantId <>", value, "tenantid");
            return (Criteria) this;
        }

        public Criteria andTenantidGreaterThan(Integer value) {
            addCriterion("tenantId >", value, "tenantid");
            return (Criteria) this;
        }

        public Criteria andTenantidGreaterThanOrEqualTo(Integer value) {
            addCriterion("tenantId >=", value, "tenantid");
            return (Criteria) this;
        }

        public Criteria andTenantidLessThan(Integer value) {
            addCriterion("tenantId <", value, "tenantid");
            return (Criteria) this;
        }

        public Criteria andTenantidLessThanOrEqualTo(Integer value) {
            addCriterion("tenantId <=", value, "tenantid");
            return (Criteria) this;
        }

        public Criteria andTenantidIn(List<Integer> values) {
            addCriterion("tenantId in", values, "tenantid");
            return (Criteria) this;
        }

        public Criteria andTenantidNotIn(List<Integer> values) {
            addCriterion("tenantId not in", values, "tenantid");
            return (Criteria) this;
        }

        public Criteria andTenantidBetween(Integer value1, Integer value2) {
            addCriterion("tenantId between", value1, value2, "tenantid");
            return (Criteria) this;
        }

        public Criteria andTenantidNotBetween(Integer value1, Integer value2) {
            addCriterion("tenantId not between", value1, value2, "tenantid");
            return (Criteria) this;
        }

        public Criteria andTransactiondateIsNull() {
            addCriterion("transactionDate is null");
            return (Criteria) this;
        }

        public Criteria andTransactiondateIsNotNull() {
            addCriterion("transactionDate is not null");
            return (Criteria) this;
        }

        public Criteria andTransactiondateEqualTo(String value) {
            addCriterion("transactionDate =", value, "transactiondate");
            return (Criteria) this;
        }

        public Criteria andTransactiondateNotEqualTo(String value) {
            addCriterion("transactionDate <>", value, "transactiondate");
            return (Criteria) this;
        }

        public Criteria andTransactiondateGreaterThan(String value) {
            addCriterion("transactionDate >", value, "transactiondate");
            return (Criteria) this;
        }

        public Criteria andTransactiondateGreaterThanOrEqualTo(String value) {
            addCriterion("transactionDate >=", value, "transactiondate");
            return (Criteria) this;
        }

        public Criteria andTransactiondateLessThan(String value) {
            addCriterion("transactionDate <", value, "transactiondate");
            return (Criteria) this;
        }

        public Criteria andTransactiondateLessThanOrEqualTo(String value) {
            addCriterion("transactionDate <=", value, "transactiondate");
            return (Criteria) this;
        }

        public Criteria andTransactiondateLike(String value) {
            addCriterion("transactionDate like", value, "transactiondate");
            return (Criteria) this;
        }

        public Criteria andTransactiondateNotLike(String value) {
            addCriterion("transactionDate not like", value, "transactiondate");
            return (Criteria) this;
        }

        public Criteria andTransactiondateIn(List<String> values) {
            addCriterion("transactionDate in", values, "transactiondate");
            return (Criteria) this;
        }

        public Criteria andTransactiondateNotIn(List<String> values) {
            addCriterion("transactionDate not in", values, "transactiondate");
            return (Criteria) this;
        }

        public Criteria andTransactiondateBetween(String value1, String value2) {
            addCriterion("transactionDate between", value1, value2, "transactiondate");
            return (Criteria) this;
        }

        public Criteria andTransactiondateNotBetween(String value1, String value2) {
            addCriterion("transactionDate not between", value1, value2, "transactiondate");
            return (Criteria) this;
        }

        public Criteria andStartmonthIsNull() {
            addCriterion("startMonth is null");
            return (Criteria) this;
        }

        public Criteria andStartmonthIsNotNull() {
            addCriterion("startMonth is not null");
            return (Criteria) this;
        }

        public Criteria andStartmonthEqualTo(String value) {
            addCriterion("startMonth =", value, "startmonth");
            return (Criteria) this;
        }

        public Criteria andStartmonthNotEqualTo(String value) {
            addCriterion("startMonth <>", value, "startmonth");
            return (Criteria) this;
        }

        public Criteria andStartmonthGreaterThan(String value) {
            addCriterion("startMonth >", value, "startmonth");
            return (Criteria) this;
        }

        public Criteria andStartmonthGreaterThanOrEqualTo(String value) {
            addCriterion("startMonth >=", value, "startmonth");
            return (Criteria) this;
        }

        public Criteria andStartmonthLessThan(String value) {
            addCriterion("startMonth <", value, "startmonth");
            return (Criteria) this;
        }

        public Criteria andStartmonthLessThanOrEqualTo(String value) {
            addCriterion("startMonth <=", value, "startmonth");
            return (Criteria) this;
        }

        public Criteria andStartmonthLike(String value) {
            addCriterion("startMonth like", value, "startmonth");
            return (Criteria) this;
        }

        public Criteria andStartmonthNotLike(String value) {
            addCriterion("startMonth not like", value, "startmonth");
            return (Criteria) this;
        }

        public Criteria andStartmonthIn(List<String> values) {
            addCriterion("startMonth in", values, "startmonth");
            return (Criteria) this;
        }

        public Criteria andStartmonthNotIn(List<String> values) {
            addCriterion("startMonth not in", values, "startmonth");
            return (Criteria) this;
        }

        public Criteria andStartmonthBetween(String value1, String value2) {
            addCriterion("startMonth between", value1, value2, "startmonth");
            return (Criteria) this;
        }

        public Criteria andStartmonthNotBetween(String value1, String value2) {
            addCriterion("startMonth not between", value1, value2, "startmonth");
            return (Criteria) this;
        }

        public Criteria andEndmonthIsNull() {
            addCriterion("endMonth is null");
            return (Criteria) this;
        }

        public Criteria andEndmonthIsNotNull() {
            addCriterion("endMonth is not null");
            return (Criteria) this;
        }

        public Criteria andEndmonthEqualTo(String value) {
            addCriterion("endMonth =", value, "endmonth");
            return (Criteria) this;
        }

        public Criteria andEndmonthNotEqualTo(String value) {
            addCriterion("endMonth <>", value, "endmonth");
            return (Criteria) this;
        }

        public Criteria andEndmonthGreaterThan(String value) {
            addCriterion("endMonth >", value, "endmonth");
            return (Criteria) this;
        }

        public Criteria andEndmonthGreaterThanOrEqualTo(String value) {
            addCriterion("endMonth >=", value, "endmonth");
            return (Criteria) this;
        }

        public Criteria andEndmonthLessThan(String value) {
            addCriterion("endMonth <", value, "endmonth");
            return (Criteria) this;
        }

        public Criteria andEndmonthLessThanOrEqualTo(String value) {
            addCriterion("endMonth <=", value, "endmonth");
            return (Criteria) this;
        }

        public Criteria andEndmonthLike(String value) {
            addCriterion("endMonth like", value, "endmonth");
            return (Criteria) this;
        }

        public Criteria andEndmonthNotLike(String value) {
            addCriterion("endMonth not like", value, "endmonth");
            return (Criteria) this;
        }

        public Criteria andEndmonthIn(List<String> values) {
            addCriterion("endMonth in", values, "endmonth");
            return (Criteria) this;
        }

        public Criteria andEndmonthNotIn(List<String> values) {
            addCriterion("endMonth not in", values, "endmonth");
            return (Criteria) this;
        }

        public Criteria andEndmonthBetween(String value1, String value2) {
            addCriterion("endMonth between", value1, value2, "endmonth");
            return (Criteria) this;
        }

        public Criteria andEndmonthNotBetween(String value1, String value2) {
            addCriterion("endMonth not between", value1, value2, "endmonth");
            return (Criteria) this;
        }

        public Criteria andDepositmoneyIsNull() {
            addCriterion("depositMoney is null");
            return (Criteria) this;
        }

        public Criteria andDepositmoneyIsNotNull() {
            addCriterion("depositMoney is not null");
            return (Criteria) this;
        }

        public Criteria andDepositmoneyEqualTo(Float value) {
            addCriterion("depositMoney =", value, "depositmoney");
            return (Criteria) this;
        }

        public Criteria andDepositmoneyNotEqualTo(Float value) {
            addCriterion("depositMoney <>", value, "depositmoney");
            return (Criteria) this;
        }

        public Criteria andDepositmoneyGreaterThan(Float value) {
            addCriterion("depositMoney >", value, "depositmoney");
            return (Criteria) this;
        }

        public Criteria andDepositmoneyGreaterThanOrEqualTo(Float value) {
            addCriterion("depositMoney >=", value, "depositmoney");
            return (Criteria) this;
        }

        public Criteria andDepositmoneyLessThan(Float value) {
            addCriterion("depositMoney <", value, "depositmoney");
            return (Criteria) this;
        }

        public Criteria andDepositmoneyLessThanOrEqualTo(Float value) {
            addCriterion("depositMoney <=", value, "depositmoney");
            return (Criteria) this;
        }

        public Criteria andDepositmoneyIn(List<Float> values) {
            addCriterion("depositMoney in", values, "depositmoney");
            return (Criteria) this;
        }

        public Criteria andDepositmoneyNotIn(List<Float> values) {
            addCriterion("depositMoney not in", values, "depositmoney");
            return (Criteria) this;
        }

        public Criteria andDepositmoneyBetween(Float value1, Float value2) {
            addCriterion("depositMoney between", value1, value2, "depositmoney");
            return (Criteria) this;
        }

        public Criteria andDepositmoneyNotBetween(Float value1, Float value2) {
            addCriterion("depositMoney not between", value1, value2, "depositmoney");
            return (Criteria) this;
        }

        public Criteria andPaymentmethodIsNull() {
            addCriterion("paymentMethod is null");
            return (Criteria) this;
        }

        public Criteria andPaymentmethodIsNotNull() {
            addCriterion("paymentMethod is not null");
            return (Criteria) this;
        }

        public Criteria andPaymentmethodEqualTo(Integer value) {
            addCriterion("paymentMethod =", value, "paymentmethod");
            return (Criteria) this;
        }

        public Criteria andPaymentmethodNotEqualTo(Integer value) {
            addCriterion("paymentMethod <>", value, "paymentmethod");
            return (Criteria) this;
        }

        public Criteria andPaymentmethodGreaterThan(Integer value) {
            addCriterion("paymentMethod >", value, "paymentmethod");
            return (Criteria) this;
        }

        public Criteria andPaymentmethodGreaterThanOrEqualTo(Integer value) {
            addCriterion("paymentMethod >=", value, "paymentmethod");
            return (Criteria) this;
        }

        public Criteria andPaymentmethodLessThan(Integer value) {
            addCriterion("paymentMethod <", value, "paymentmethod");
            return (Criteria) this;
        }

        public Criteria andPaymentmethodLessThanOrEqualTo(Integer value) {
            addCriterion("paymentMethod <=", value, "paymentmethod");
            return (Criteria) this;
        }

        public Criteria andPaymentmethodIn(List<Integer> values) {
            addCriterion("paymentMethod in", values, "paymentmethod");
            return (Criteria) this;
        }

        public Criteria andPaymentmethodNotIn(List<Integer> values) {
            addCriterion("paymentMethod not in", values, "paymentmethod");
            return (Criteria) this;
        }

        public Criteria andPaymentmethodBetween(Integer value1, Integer value2) {
            addCriterion("paymentMethod between", value1, value2, "paymentmethod");
            return (Criteria) this;
        }

        public Criteria andPaymentmethodNotBetween(Integer value1, Integer value2) {
            addCriterion("paymentMethod not between", value1, value2, "paymentmethod");
            return (Criteria) this;
        }

        public Criteria andMonthrentIsNull() {
            addCriterion("monthRent is null");
            return (Criteria) this;
        }

        public Criteria andMonthrentIsNotNull() {
            addCriterion("monthRent is not null");
            return (Criteria) this;
        }

        public Criteria andMonthrentEqualTo(Float value) {
            addCriterion("monthRent =", value, "monthrent");
            return (Criteria) this;
        }

        public Criteria andMonthrentNotEqualTo(Float value) {
            addCriterion("monthRent <>", value, "monthrent");
            return (Criteria) this;
        }

        public Criteria andMonthrentGreaterThan(Float value) {
            addCriterion("monthRent >", value, "monthrent");
            return (Criteria) this;
        }

        public Criteria andMonthrentGreaterThanOrEqualTo(Float value) {
            addCriterion("monthRent >=", value, "monthrent");
            return (Criteria) this;
        }

        public Criteria andMonthrentLessThan(Float value) {
            addCriterion("monthRent <", value, "monthrent");
            return (Criteria) this;
        }

        public Criteria andMonthrentLessThanOrEqualTo(Float value) {
            addCriterion("monthRent <=", value, "monthrent");
            return (Criteria) this;
        }

        public Criteria andMonthrentIn(List<Float> values) {
            addCriterion("monthRent in", values, "monthrent");
            return (Criteria) this;
        }

        public Criteria andMonthrentNotIn(List<Float> values) {
            addCriterion("monthRent not in", values, "monthrent");
            return (Criteria) this;
        }

        public Criteria andMonthrentBetween(Float value1, Float value2) {
            addCriterion("monthRent between", value1, value2, "monthrent");
            return (Criteria) this;
        }

        public Criteria andMonthrentNotBetween(Float value1, Float value2) {
            addCriterion("monthRent not between", value1, value2, "monthrent");
            return (Criteria) this;
        }

        public Criteria andTotalrentIsNull() {
            addCriterion("totalRent is null");
            return (Criteria) this;
        }

        public Criteria andTotalrentIsNotNull() {
            addCriterion("totalRent is not null");
            return (Criteria) this;
        }

        public Criteria andTotalrentEqualTo(Float value) {
            addCriterion("totalRent =", value, "totalrent");
            return (Criteria) this;
        }

        public Criteria andTotalrentNotEqualTo(Float value) {
            addCriterion("totalRent <>", value, "totalrent");
            return (Criteria) this;
        }

        public Criteria andTotalrentGreaterThan(Float value) {
            addCriterion("totalRent >", value, "totalrent");
            return (Criteria) this;
        }

        public Criteria andTotalrentGreaterThanOrEqualTo(Float value) {
            addCriterion("totalRent >=", value, "totalrent");
            return (Criteria) this;
        }

        public Criteria andTotalrentLessThan(Float value) {
            addCriterion("totalRent <", value, "totalrent");
            return (Criteria) this;
        }

        public Criteria andTotalrentLessThanOrEqualTo(Float value) {
            addCriterion("totalRent <=", value, "totalrent");
            return (Criteria) this;
        }

        public Criteria andTotalrentIn(List<Float> values) {
            addCriterion("totalRent in", values, "totalrent");
            return (Criteria) this;
        }

        public Criteria andTotalrentNotIn(List<Float> values) {
            addCriterion("totalRent not in", values, "totalrent");
            return (Criteria) this;
        }

        public Criteria andTotalrentBetween(Float value1, Float value2) {
            addCriterion("totalRent between", value1, value2, "totalrent");
            return (Criteria) this;
        }

        public Criteria andTotalrentNotBetween(Float value1, Float value2) {
            addCriterion("totalRent not between", value1, value2, "totalrent");
            return (Criteria) this;
        }

        public Criteria andLandlordpaymentagencyfeeIsNull() {
            addCriterion("landlordPaymentAgencyFee is null");
            return (Criteria) this;
        }

        public Criteria andLandlordpaymentagencyfeeIsNotNull() {
            addCriterion("landlordPaymentAgencyFee is not null");
            return (Criteria) this;
        }

        public Criteria andLandlordpaymentagencyfeeEqualTo(Float value) {
            addCriterion("landlordPaymentAgencyFee =", value, "landlordpaymentagencyfee");
            return (Criteria) this;
        }

        public Criteria andLandlordpaymentagencyfeeNotEqualTo(Float value) {
            addCriterion("landlordPaymentAgencyFee <>", value, "landlordpaymentagencyfee");
            return (Criteria) this;
        }

        public Criteria andLandlordpaymentagencyfeeGreaterThan(Float value) {
            addCriterion("landlordPaymentAgencyFee >", value, "landlordpaymentagencyfee");
            return (Criteria) this;
        }

        public Criteria andLandlordpaymentagencyfeeGreaterThanOrEqualTo(Float value) {
            addCriterion("landlordPaymentAgencyFee >=", value, "landlordpaymentagencyfee");
            return (Criteria) this;
        }

        public Criteria andLandlordpaymentagencyfeeLessThan(Float value) {
            addCriterion("landlordPaymentAgencyFee <", value, "landlordpaymentagencyfee");
            return (Criteria) this;
        }

        public Criteria andLandlordpaymentagencyfeeLessThanOrEqualTo(Float value) {
            addCriterion("landlordPaymentAgencyFee <=", value, "landlordpaymentagencyfee");
            return (Criteria) this;
        }

        public Criteria andLandlordpaymentagencyfeeIn(List<Float> values) {
            addCriterion("landlordPaymentAgencyFee in", values, "landlordpaymentagencyfee");
            return (Criteria) this;
        }

        public Criteria andLandlordpaymentagencyfeeNotIn(List<Float> values) {
            addCriterion("landlordPaymentAgencyFee not in", values, "landlordpaymentagencyfee");
            return (Criteria) this;
        }

        public Criteria andLandlordpaymentagencyfeeBetween(Float value1, Float value2) {
            addCriterion("landlordPaymentAgencyFee between", value1, value2, "landlordpaymentagencyfee");
            return (Criteria) this;
        }

        public Criteria andLandlordpaymentagencyfeeNotBetween(Float value1, Float value2) {
            addCriterion("landlordPaymentAgencyFee not between", value1, value2, "landlordpaymentagencyfee");
            return (Criteria) this;
        }

        public Criteria andTenantpaymentagencyfeeIsNull() {
            addCriterion("tenantPaymentAgencyFee is null");
            return (Criteria) this;
        }

        public Criteria andTenantpaymentagencyfeeIsNotNull() {
            addCriterion("tenantPaymentAgencyFee is not null");
            return (Criteria) this;
        }

        public Criteria andTenantpaymentagencyfeeEqualTo(Float value) {
            addCriterion("tenantPaymentAgencyFee =", value, "tenantpaymentagencyfee");
            return (Criteria) this;
        }

        public Criteria andTenantpaymentagencyfeeNotEqualTo(Float value) {
            addCriterion("tenantPaymentAgencyFee <>", value, "tenantpaymentagencyfee");
            return (Criteria) this;
        }

        public Criteria andTenantpaymentagencyfeeGreaterThan(Float value) {
            addCriterion("tenantPaymentAgencyFee >", value, "tenantpaymentagencyfee");
            return (Criteria) this;
        }

        public Criteria andTenantpaymentagencyfeeGreaterThanOrEqualTo(Float value) {
            addCriterion("tenantPaymentAgencyFee >=", value, "tenantpaymentagencyfee");
            return (Criteria) this;
        }

        public Criteria andTenantpaymentagencyfeeLessThan(Float value) {
            addCriterion("tenantPaymentAgencyFee <", value, "tenantpaymentagencyfee");
            return (Criteria) this;
        }

        public Criteria andTenantpaymentagencyfeeLessThanOrEqualTo(Float value) {
            addCriterion("tenantPaymentAgencyFee <=", value, "tenantpaymentagencyfee");
            return (Criteria) this;
        }

        public Criteria andTenantpaymentagencyfeeIn(List<Float> values) {
            addCriterion("tenantPaymentAgencyFee in", values, "tenantpaymentagencyfee");
            return (Criteria) this;
        }

        public Criteria andTenantpaymentagencyfeeNotIn(List<Float> values) {
            addCriterion("tenantPaymentAgencyFee not in", values, "tenantpaymentagencyfee");
            return (Criteria) this;
        }

        public Criteria andTenantpaymentagencyfeeBetween(Float value1, Float value2) {
            addCriterion("tenantPaymentAgencyFee between", value1, value2, "tenantpaymentagencyfee");
            return (Criteria) this;
        }

        public Criteria andTenantpaymentagencyfeeNotBetween(Float value1, Float value2) {
            addCriterion("tenantPaymentAgencyFee not between", value1, value2, "tenantpaymentagencyfee");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rentsystem..renttransaction
     *
     * @mbggenerated do_not_delete_during_merge Sat Jan 05 21:07:16 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rentsystem..renttransaction
     *
     * @mbggenerated Sat Jan 05 21:07:16 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}