package com.rent.entity;

public class RentTransaction {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rentsystem..renttransaction.transactionId
     *
     * @mbggenerated Sat Jan 05 20:49:53 CST 2019
     */
    private Integer transactionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rentsystem..renttransaction.houseId
     *
     * @mbggenerated Sat Jan 05 20:49:53 CST 2019
     */
    private Integer houseid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rentsystem..renttransaction.landlordId
     *
     * @mbggenerated Sat Jan 05 20:49:53 CST 2019
     */
    private Integer landlordid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rentsystem..renttransaction.tenantId
     *
     * @mbggenerated Sat Jan 05 20:49:53 CST 2019
     */
    private Integer tenantid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rentsystem..renttransaction.transactionDate
     *
     * @mbggenerated Sat Jan 05 20:49:53 CST 2019
     */
    private String transactiondate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rentsystem..renttransaction.startMonth
     *
     * @mbggenerated Sat Jan 05 20:49:53 CST 2019
     */
    private String startmonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rentsystem..renttransaction.endMonth
     *
     * @mbggenerated Sat Jan 05 20:49:53 CST 2019
     */
    private String endmonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rentsystem..renttransaction.depositMoney
     *
     * @mbggenerated Sat Jan 05 20:49:53 CST 2019
     */
    private Float depositmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rentsystem..renttransaction.paymentMethod
     *
     * @mbggenerated Sat Jan 05 20:49:53 CST 2019
     */
    private Integer paymentmethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rentsystem..renttransaction.monthRent
     *
     * @mbggenerated Sat Jan 05 20:49:53 CST 2019
     */
    private Float monthrent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rentsystem..renttransaction.totalRent
     *
     * @mbggenerated Sat Jan 05 20:49:53 CST 2019
     */
    private Float totalrent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rentsystem..renttransaction.landlordPaymentAgencyFee
     *
     * @mbggenerated Sat Jan 05 20:49:53 CST 2019
     */
    private Float landlordpaymentagencyfee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rentsystem..renttransaction.tenantPaymentAgencyFee
     *
     * @mbggenerated Sat Jan 05 20:49:53 CST 2019
     */
    private Float tenantpaymentagencyfee;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rentsystem..renttransaction.transactionId
     *
     * @return the value of rentsystem..renttransaction.transactionId
     *
     * @mbggenerated Sat Jan 05 20:49:53 CST 2019
     */
    public Integer getTransactionid() {
        return transactionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rentsystem..renttransaction.transactionId
     *
     * @param transactionid the value for rentsystem..renttransaction.transactionId
     *
     * @mbggenerated Sat Jan 05 20:49:53 CST 2019
     */
    public void setTransactionid(Integer transactionid) {
        this.transactionid = transactionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rentsystem..renttransaction.houseId
     *
     * @return the value of rentsystem..renttransaction.houseId
     *
     * @mbggenerated Sat Jan 05 20:49:53 CST 2019
     */
    public Integer getHouseid() {
        return houseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rentsystem..renttransaction.houseId
     *
     * @param houseid the value for rentsystem..renttransaction.houseId
     *
     * @mbggenerated Sat Jan 05 20:49:53 CST 2019
     */
    public void setHouseid(Integer houseid) {
        this.houseid = houseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rentsystem..renttransaction.landlordId
     *
     * @return the value of rentsystem..renttransaction.landlordId
     *
     * @mbggenerated Sat Jan 05 20:49:53 CST 2019
     */
    public Integer getLandlordid() {
        return landlordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rentsystem..renttransaction.landlordId
     *
     * @param landlordid the value for rentsystem..renttransaction.landlordId
     *
     * @mbggenerated Sat Jan 05 20:49:53 CST 2019
     */
    public void setLandlordid(Integer landlordid) {
        this.landlordid = landlordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rentsystem..renttransaction.tenantId
     *
     * @return the value of rentsystem..renttransaction.tenantId
     *
     * @mbggenerated Sat Jan 05 20:49:53 CST 2019
     */
    public Integer getTenantid() {
        return tenantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rentsystem..renttransaction.tenantId
     *
     * @param tenantid the value for rentsystem..renttransaction.tenantId
     *
     * @mbggenerated Sat Jan 05 20:49:53 CST 2019
     */
    public void setTenantid(Integer tenantid) {
        this.tenantid = tenantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rentsystem..renttransaction.transactionDate
     *
     * @return the value of rentsystem..renttransaction.transactionDate
     *
     * @mbggenerated Sat Jan 05 20:49:53 CST 2019
     */
    public String getTransactiondate() {
        return transactiondate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rentsystem..renttransaction.transactionDate
     *
     * @param transactiondate the value for rentsystem..renttransaction.transactionDate
     *
     * @mbggenerated Sat Jan 05 20:49:53 CST 2019
     */
    public void setTransactiondate(String transactiondate) {
        this.transactiondate = transactiondate == null ? null : transactiondate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rentsystem..renttransaction.startMonth
     *
     * @return the value of rentsystem..renttransaction.startMonth
     *
     * @mbggenerated Sat Jan 05 20:49:53 CST 2019
     */
    public String getStartmonth() {
        return startmonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rentsystem..renttransaction.startMonth
     *
     * @param startmonth the value for rentsystem..renttransaction.startMonth
     *
     * @mbggenerated Sat Jan 05 20:49:53 CST 2019
     */
    public void setStartmonth(String startmonth) {
        this.startmonth = startmonth == null ? null : startmonth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rentsystem..renttransaction.endMonth
     *
     * @return the value of rentsystem..renttransaction.endMonth
     *
     * @mbggenerated Sat Jan 05 20:49:53 CST 2019
     */
    public String getEndmonth() {
        return endmonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rentsystem..renttransaction.endMonth
     *
     * @param endmonth the value for rentsystem..renttransaction.endMonth
     *
     * @mbggenerated Sat Jan 05 20:49:53 CST 2019
     */
    public void setEndmonth(String endmonth) {
        this.endmonth = endmonth == null ? null : endmonth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rentsystem..renttransaction.depositMoney
     *
     * @return the value of rentsystem..renttransaction.depositMoney
     *
     * @mbggenerated Sat Jan 05 20:49:53 CST 2019
     */
    public Float getDepositmoney() {
        return depositmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rentsystem..renttransaction.depositMoney
     *
     * @param depositmoney the value for rentsystem..renttransaction.depositMoney
     *
     * @mbggenerated Sat Jan 05 20:49:53 CST 2019
     */
    public void setDepositmoney(Float depositmoney) {
        this.depositmoney = depositmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rentsystem..renttransaction.paymentMethod
     *
     * @return the value of rentsystem..renttransaction.paymentMethod
     *
     * @mbggenerated Sat Jan 05 20:49:53 CST 2019
     */
    public Integer getPaymentmethod() {
        return paymentmethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rentsystem..renttransaction.paymentMethod
     *
     * @param paymentmethod the value for rentsystem..renttransaction.paymentMethod
     *
     * @mbggenerated Sat Jan 05 20:49:53 CST 2019
     */
    public void setPaymentmethod(Integer paymentmethod) {
        this.paymentmethod = paymentmethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rentsystem..renttransaction.monthRent
     *
     * @return the value of rentsystem..renttransaction.monthRent
     *
     * @mbggenerated Sat Jan 05 20:49:53 CST 2019
     */
    public Float getMonthrent() {
        return monthrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rentsystem..renttransaction.monthRent
     *
     * @param monthrent the value for rentsystem..renttransaction.monthRent
     *
     * @mbggenerated Sat Jan 05 20:49:53 CST 2019
     */
    public void setMonthrent(Float monthrent) {
        this.monthrent = monthrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rentsystem..renttransaction.totalRent
     *
     * @return the value of rentsystem..renttransaction.totalRent
     *
     * @mbggenerated Sat Jan 05 20:49:53 CST 2019
     */
    public Float getTotalrent() {
        return totalrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rentsystem..renttransaction.totalRent
     *
     * @param totalrent the value for rentsystem..renttransaction.totalRent
     *
     * @mbggenerated Sat Jan 05 20:49:53 CST 2019
     */
    public void setTotalrent(Float totalrent) {
        this.totalrent = totalrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rentsystem..renttransaction.landlordPaymentAgencyFee
     *
     * @return the value of rentsystem..renttransaction.landlordPaymentAgencyFee
     *
     * @mbggenerated Sat Jan 05 20:49:53 CST 2019
     */
    public Float getLandlordpaymentagencyfee() {
        return landlordpaymentagencyfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rentsystem..renttransaction.landlordPaymentAgencyFee
     *
     * @param landlordpaymentagencyfee the value for rentsystem..renttransaction.landlordPaymentAgencyFee
     *
     * @mbggenerated Sat Jan 05 20:49:53 CST 2019
     */
    public void setLandlordpaymentagencyfee(Float landlordpaymentagencyfee) {
        this.landlordpaymentagencyfee = landlordpaymentagencyfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rentsystem..renttransaction.tenantPaymentAgencyFee
     *
     * @return the value of rentsystem..renttransaction.tenantPaymentAgencyFee
     *
     * @mbggenerated Sat Jan 05 20:49:53 CST 2019
     */
    public Float getTenantpaymentagencyfee() {
        return tenantpaymentagencyfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rentsystem..renttransaction.tenantPaymentAgencyFee
     *
     * @param tenantpaymentagencyfee the value for rentsystem..renttransaction.tenantPaymentAgencyFee
     *
     * @mbggenerated Sat Jan 05 20:49:53 CST 2019
     */
    public void setTenantpaymentagencyfee(Float tenantpaymentagencyfee) {
        this.tenantpaymentagencyfee = tenantpaymentagencyfee;
    }
}