package com.rent.dao;

import com.rent.entity.House;
import com.rent.entity.HouseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HouseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..house
     *
     * @mbggenerated Tue Dec 25 16:44:53 CST 2018
     */
    int countByExample(HouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..house
     *
     * @mbggenerated Tue Dec 25 16:44:53 CST 2018
     */
    int deleteByExample(HouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..house
     *
     * @mbggenerated Tue Dec 25 16:44:53 CST 2018
     */
    int deleteByPrimaryKey(Integer houseid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..house
     *
     * @mbggenerated Tue Dec 25 16:44:53 CST 2018
     */
    int insert(House record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..house
     *
     * @mbggenerated Tue Dec 25 16:44:53 CST 2018
     */
    int insertSelective(House record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..house
     *
     * @mbggenerated Tue Dec 25 16:44:53 CST 2018
     */
    List<House> selectByExample(HouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..house
     *
     * @mbggenerated Tue Dec 25 16:44:53 CST 2018
     */
    House selectByPrimaryKey(Integer houseid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..house
     *
     * @mbggenerated Tue Dec 25 16:44:53 CST 2018
     */
    int updateByExampleSelective(@Param("record") House record, @Param("example") HouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..house
     *
     * @mbggenerated Tue Dec 25 16:44:53 CST 2018
     */
    int updateByExample(@Param("record") House record, @Param("example") HouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..house
     *
     * @mbggenerated Tue Dec 25 16:44:53 CST 2018
     */
    int updateByPrimaryKeySelective(House record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..house
     *
     * @mbggenerated Tue Dec 25 16:44:53 CST 2018
     */
    int updateByPrimaryKey(House record);
}