package com.rent.dao;

import com.rent.entity.Income;
import com.rent.entity.IncomeExample;
import com.rent.entity.IncomeKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IncomeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..income
     *
     * @mbggenerated Tue Dec 25 16:44:53 CST 2018
     */
    int countByExample(IncomeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..income
     *
     * @mbggenerated Tue Dec 25 16:44:53 CST 2018
     */
    int deleteByExample(IncomeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..income
     *
     * @mbggenerated Tue Dec 25 16:44:53 CST 2018
     */
    int deleteByPrimaryKey(IncomeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..income
     *
     * @mbggenerated Tue Dec 25 16:44:53 CST 2018
     */
    int insert(Income record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..income
     *
     * @mbggenerated Tue Dec 25 16:44:53 CST 2018
     */
    int insertSelective(Income record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..income
     *
     * @mbggenerated Tue Dec 25 16:44:53 CST 2018
     */
    List<Income> selectByExample(IncomeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..income
     *
     * @mbggenerated Tue Dec 25 16:44:53 CST 2018
     */
    Income selectByPrimaryKey(IncomeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..income
     *
     * @mbggenerated Tue Dec 25 16:44:53 CST 2018
     */
    int updateByExampleSelective(@Param("record") Income record, @Param("example") IncomeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..income
     *
     * @mbggenerated Tue Dec 25 16:44:53 CST 2018
     */
    int updateByExample(@Param("record") Income record, @Param("example") IncomeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..income
     *
     * @mbggenerated Tue Dec 25 16:44:53 CST 2018
     */
    int updateByPrimaryKeySelective(Income record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..income
     *
     * @mbggenerated Tue Dec 25 16:44:53 CST 2018
     */
    int updateByPrimaryKey(Income record);
}