package com.rent.dao;

import com.rent.entity.Photo;
import com.rent.entity.PhotoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PhotoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..photo
     *
     * @mbggenerated Fri Jan 11 18:01:24 CST 2019
     */
    int countByExample(PhotoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..photo
     *
     * @mbggenerated Fri Jan 11 18:01:24 CST 2019
     */
    int deleteByExample(PhotoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..photo
     *
     * @mbggenerated Fri Jan 11 18:01:24 CST 2019
     */
    int deleteByPrimaryKey(Integer photoid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..photo
     *
     * @mbggenerated Fri Jan 11 18:01:24 CST 2019
     */
    int insert(Photo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..photo
     *
     * @mbggenerated Fri Jan 11 18:01:24 CST 2019
     */
    int insertSelective(Photo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..photo
     *
     * @mbggenerated Fri Jan 11 18:01:24 CST 2019
     */
    List<Photo> selectByExample(PhotoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..photo
     *
     * @mbggenerated Fri Jan 11 18:01:24 CST 2019
     */
    Photo selectByPrimaryKey(Integer photoid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..photo
     *
     * @mbggenerated Fri Jan 11 18:01:24 CST 2019
     */
    int updateByExampleSelective(@Param("record") Photo record, @Param("example") PhotoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..photo
     *
     * @mbggenerated Fri Jan 11 18:01:24 CST 2019
     */
    int updateByExample(@Param("record") Photo record, @Param("example") PhotoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..photo
     *
     * @mbggenerated Fri Jan 11 18:01:24 CST 2019
     */
    int updateByPrimaryKeySelective(Photo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..photo
     *
     * @mbggenerated Fri Jan 11 18:01:24 CST 2019
     */
    int updateByPrimaryKey(Photo record);
}