package com.rent.dao;

import com.rent.entity.RentInformation;
import com.rent.entity.RentInformationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RentInformationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..rentinformation
     *
     * @mbggenerated Tue Dec 25 16:44:53 CST 2018
     */
    int countByExample(RentInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..rentinformation
     *
     * @mbggenerated Tue Dec 25 16:44:53 CST 2018
     */
    int deleteByExample(RentInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..rentinformation
     *
     * @mbggenerated Tue Dec 25 16:44:53 CST 2018
     */
    int deleteByPrimaryKey(Integer rentid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..rentinformation
     *
     * @mbggenerated Tue Dec 25 16:44:53 CST 2018
     */
    int insert(RentInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..rentinformation
     *
     * @mbggenerated Tue Dec 25 16:44:53 CST 2018
     */
    int insertSelective(RentInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..rentinformation
     *
     * @mbggenerated Tue Dec 25 16:44:53 CST 2018
     */
    List<RentInformation> selectByExample(RentInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..rentinformation
     *
     * @mbggenerated Tue Dec 25 16:44:53 CST 2018
     */
    RentInformation selectByPrimaryKey(Integer rentid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..rentinformation
     *
     * @mbggenerated Tue Dec 25 16:44:53 CST 2018
     */
    int updateByExampleSelective(@Param("record") RentInformation record, @Param("example") RentInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..rentinformation
     *
     * @mbggenerated Tue Dec 25 16:44:53 CST 2018
     */
    int updateByExample(@Param("record") RentInformation record, @Param("example") RentInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..rentinformation
     *
     * @mbggenerated Tue Dec 25 16:44:53 CST 2018
     */
    int updateByPrimaryKeySelective(RentInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..rentinformation
     *
     * @mbggenerated Tue Dec 25 16:44:53 CST 2018
     */
    int updateByPrimaryKey(RentInformation record);
}