package com.rent.dao;

import com.rent.entity.RentInformation;

public interface RentInformationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..rentinformation
     *
     * @mbggenerated Tue Dec 25 13:12:59 CST 2018
     */
    int deleteByPrimaryKey(Integer rentid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..rentinformation
     *
     * @mbggenerated Tue Dec 25 13:12:59 CST 2018
     */
    int insert(RentInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..rentinformation
     *
     * @mbggenerated Tue Dec 25 13:12:59 CST 2018
     */
    int insertSelective(RentInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..rentinformation
     *
     * @mbggenerated Tue Dec 25 13:12:59 CST 2018
     */
    RentInformation selectByPrimaryKey(Integer rentid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..rentinformation
     *
     * @mbggenerated Tue Dec 25 13:12:59 CST 2018
     */
    int updateByPrimaryKeySelective(RentInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..rentinformation
     *
     * @mbggenerated Tue Dec 25 13:12:59 CST 2018
     */
    int updateByPrimaryKey(RentInformation record);
}