package com.rent.dao;

import com.rent.entity.RentTransaction;
import com.rent.entity.RentTransactionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RentTransactionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..renttransaction
     *
     * @mbggenerated Tue Dec 25 16:44:53 CST 2018
     */
    int countByExample(RentTransactionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..renttransaction
     *
     * @mbggenerated Tue Dec 25 16:44:53 CST 2018
     */
    int deleteByExample(RentTransactionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..renttransaction
     *
     * @mbggenerated Tue Dec 25 16:44:53 CST 2018
     */
    int deleteByPrimaryKey(Integer transactionid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..renttransaction
     *
     * @mbggenerated Tue Dec 25 16:44:53 CST 2018
     */
    int insert(RentTransaction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..renttransaction
     *
     * @mbggenerated Tue Dec 25 16:44:53 CST 2018
     */
    int insertSelective(RentTransaction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..renttransaction
     *
     * @mbggenerated Tue Dec 25 16:44:53 CST 2018
     */
    List<RentTransaction> selectByExample(RentTransactionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..renttransaction
     *
     * @mbggenerated Tue Dec 25 16:44:53 CST 2018
     */
    RentTransaction selectByPrimaryKey(Integer transactionid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..renttransaction
     *
     * @mbggenerated Tue Dec 25 16:44:53 CST 2018
     */
    int updateByExampleSelective(@Param("record") RentTransaction record, @Param("example") RentTransactionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..renttransaction
     *
     * @mbggenerated Tue Dec 25 16:44:53 CST 2018
     */
    int updateByExample(@Param("record") RentTransaction record, @Param("example") RentTransactionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..renttransaction
     *
     * @mbggenerated Tue Dec 25 16:44:53 CST 2018
     */
    int updateByPrimaryKeySelective(RentTransaction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..renttransaction
     *
     * @mbggenerated Tue Dec 25 16:44:53 CST 2018
     */
    int updateByPrimaryKey(RentTransaction record);
}