package com.rent.dao;

import com.rent.entity.User;
import com.rent.entity.UserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..user
     *
     * @mbggenerated Tue Dec 25 16:44:53 CST 2018
     */
    int countByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..user
     *
     * @mbggenerated Tue Dec 25 16:44:53 CST 2018
     */
    int deleteByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..user
     *
     * @mbggenerated Tue Dec 25 16:44:53 CST 2018
     */
    int deleteByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..user
     *
     * @mbggenerated Tue Dec 25 16:44:53 CST 2018
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..user
     *
     * @mbggenerated Tue Dec 25 16:44:53 CST 2018
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..user
     *
     * @mbggenerated Tue Dec 25 16:44:53 CST 2018
     */
    List<User> selectByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..user
     *
     * @mbggenerated Tue Dec 25 16:44:53 CST 2018
     */
    User selectByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..user
     *
     * @mbggenerated Tue Dec 25 16:44:53 CST 2018
     */
    int updateByExampleSelective(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..user
     *
     * @mbggenerated Tue Dec 25 16:44:53 CST 2018
     */
    int updateByExample(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..user
     *
     * @mbggenerated Tue Dec 25 16:44:53 CST 2018
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..user
     *
     * @mbggenerated Tue Dec 25 16:44:53 CST 2018
     */
    int updateByPrimaryKey(User record);
}