package com.rent.dao;

import com.rent.entity.User;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..user
     *
     * @mbggenerated Tue Dec 25 13:12:59 CST 2018
     */
    int deleteByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..user
     *
     * @mbggenerated Tue Dec 25 13:12:59 CST 2018
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..user
     *
     * @mbggenerated Tue Dec 25 13:12:59 CST 2018
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..user
     *
     * @mbggenerated Tue Dec 25 13:12:59 CST 2018
     */
    User selectByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..user
     *
     * @mbggenerated Tue Dec 25 13:12:59 CST 2018
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rentsystem..user
     *
     * @mbggenerated Tue Dec 25 13:12:59 CST 2018
     */
    int updateByPrimaryKey(User record);
}